window.CHAPTER_DATA = window.CHAPTER_DATA || {};
window.CHAPTER_DATA[1] = window.CHAPTER_DATA[1] || {};
window.CHAPTER_DATA[1].questions = [
    {id:'CAST1', level:0, title:'int → double 자동 형변환',
     concept:'더 작은 범위의 타입에서 더 큰 범위의 타입으로 옮겨 담을 때는, 자바가 알아서 변환해줍니다. 따로 표시를 해주지 않아도 됩니다.',
     before:['int a = 7;'], placeholder:['// TODO: a를 double 타입 b에 대입'],
     after:['System.out.println(b);'],
     expected:'7.0', answer:['double b = a;'], note:'',
     regex:[/double\s*b\s*=\s*a\s*;?/]},

    {id:'CAST2', level:0, title:'double → int 명시적 캐스팅',
     concept:'반대로 더 큰 범위에서 더 작은 범위로 옮길 때는 정보 손실 가능성이 있어서, 괄호로 타입을 명시해 "이 손실을 감수하겠다"고 알려줘야 합니다.',
     before:['double d = 3.9;'], placeholder:['// TODO: d를 int로 캐스팅해서 i에 저장'],
     after:['System.out.println(i);'],
     expected:'3', answer:['int i = (int) d;'],
     note:'소수점 이하는 반올림되지 않고 그냥 버려집니다(truncation). 3.9가 4가 아니라 3이 되는 이유입니다.',
     regex:[/int\s*i\s*=\s*\(\s*int\s*\)\s*d\s*;?/]},

    {id:'CAST3', level:0, title:'⚠️ 함정: 정수 나눗셈의 소수점',
     concept:'두 정수(int)를 나누면, 결과도 int로 계산되어 소수점 이하가 잘립니다. 둘 중 하나라도 double로 만들어야 소수점이 살아남습니다.',
     before:['int a = 7, b = 2;'], placeholder:['// TODO: 정수 나눗셈의 소수점까지 살려서 result에 저장 (double)'],
     after:['System.out.println(result);'],
     expected:'3.5', answer:['double result = (double) a / b;'],
     note:'(double) a / b처럼 둘 중 하나만 캐스팅해도 전체 연산이 double 연산으로 승격됩니다. 반대로 a / b를 먼저 계산한 뒤 double로 캐스팅하면 이미 정수 나눗셈이 끝난 뒤라 3.0이 됩니다.',
     regex:[/double\s*result\s*=\s*\(\s*double\s*\)\s*a\s*\/\s*b\s*;?/]},

    {id:'CAST4', level:0, title:'char 연산 결과를 다시 char로',
     concept:'char는 사실 내부적으로 정수(유니코드 코드값)로 저장됩니다. char에 정수를 더하면 그 정수만큼 코드값이 이동한 결과가 int로 나오는데, 이를 다시 char로 받으려면 캐스팅이 필요합니다.',
     before:['char c = \'a\';'], placeholder:['// TODO: c에서 알파벳 2칸 뒤 문자를 ch2에 저장 (char)'],
     after:['System.out.println(ch2);'],
     expected:'c', answer:['char ch2 = (char) (c + 2);'],
     note:'char + int 연산 결과는 자동으로 int로 승격되기 때문에, 다시 char에 담으려면 명시적 캐스팅이 필요합니다.',
     regex:[/char\s*ch2\s*=\s*\(\s*char\s*\)\s*\(\s*c\s*\+\s*2\s*\)\s*;?/]},

    {id:'CAST5', level:0, title:'int → String 변환 (문자열 덧셈)',
     concept:'숫자를 문자열로 바꾸는 가장 간단한 방법은, 빈 문자열을 더하는 것입니다. 자바가 자동으로 문자열 변환을 해줍니다.',
     before:['int num = 42;'], placeholder:['// TODO: num을 문자열로 변환해 str에 저장 (빈 문자열 덧셈 이용)'],
     after:['System.out.println(str);'],
     expected:'42', answer:['String str = "" + num;'], note:'',
     regex:[/String\s*str\s*=\s*""\s*\+\s*num\s*;?/]},

    {id:'CAST6', level:0, title:'int → String 변환 (표준 메서드)',
     concept:'""를 더하는 방식 말고, 의도가 더 명확하게 드러나는 표준 메서드가 따로 있습니다. 정적(static) 메서드라서 클래스 이름으로 바로 호출합니다.',
     before:['int num = 42;'], placeholder:['// TODO: String.valueOf를 이용해 num을 문자열로 변환'],
     after:['System.out.println(str);'],
     expected:'42', answer:['String str = String.valueOf(num);'],
     note:'Integer.toString(num)도 동일하게 동작합니다.',
     regex:[/String\s*str\s*=\s*String\.valueOf\s*\(\s*num\s*\)\s*;?/]},

    {id:'CAST7', level:0, title:'char → int (유니코드 코드값)',
     concept:'반대로 char를 int로 캐스팅하면, 해당 문자의 유니코드 코드값을 숫자로 얻을 수 있습니다.',
     before:['char c = \'A\';'], placeholder:['// TODO: c의 유니코드 코드값을 code에 저장 (int)'],
     after:['System.out.println(code);'],
     expected:'65', answer:['int code = (int) c;'], note:'',
     regex:[/int\s*code\s*=\s*\(\s*int\s*\)\s*c\s*;?/]},

    {id:'PARSE1', level:1, title:'String → int (Integer.parseInt)',
     concept:'문자열로 들어온 숫자를 실제 계산에 쓰려면, 정수로 파싱(parsing)해야 합니다. 정적 메서드를 이용합니다.',
     before:['String str = "123";'], placeholder:['// TODO: str을 정수로 변환해 num에 저장'],
     after:['System.out.println(num + 1);'],
     expected:'124', answer:['int num = Integer.parseInt(str);'], note:'',
     regex:[/int\s*num\s*=\s*Integer\.parseInt\s*\(\s*str\s*\)\s*;?/]},

    {id:'PARSE2', level:1, title:'String → double (Double.parseDouble)',
     concept:'정수가 아니라 실수 형태의 문자열을 변환하고 싶을 때 쓰는, parseInt와 짝을 이루는 메서드가 있습니다.',
     before:['String str = "3.14";'], placeholder:['// TODO: str을 double로 변환해 d에 저장'],
     after:['System.out.println(d);'],
     expected:'3.14', answer:['double d = Double.parseDouble(str);'], note:'',
     regex:[/double\s*d\s*=\s*Double\.parseDouble\s*\(\s*str\s*\)\s*;?/]},

    {id:'PARSE3', level:1, title:'char[] → String 변환',
     concept:'char 배열을 하나의 문자열로 합치고 싶을 때 쓰는 생성자가 있습니다.',
     before:['char[] chars = {\'h\',\'i\'};'], placeholder:['// TODO: chars를 합쳐서 String s로 만들기'],
     after:['System.out.println(s);'],
     expected:'hi', answer:['String s = new String(chars);'], note:'',
     regex:[/String\s*s\s*=\s*new\s*String\s*\(\s*chars\s*\)\s*;?/]},

    {id:'PARSE4', level:1, title:'String → char[] 변환',
     concept:'반대로 문자열을 한 글자씩 다루고 싶을 때, char 배열로 쪼개주는 메서드가 있습니다.',
     before:['String s = "hi";'], placeholder:['// TODO: s를 char 배열 chars로 변환'],
     after:['System.out.println(chars.length);'],
     expected:'2', answer:['char[] chars = s.toCharArray();'], note:'',
     regex:[/char\s*\[\s*\]\s*chars\s*=\s*s\.toCharArray\s*\(\s*\)\s*;?/]},

    {id:'PARSE5', level:1, title:'Wrapper 객체에서 기본형 꺼내기',
     concept:'Integer 객체에서 int 값을 직접 꺼내는 메서드가 있습니다 (보통은 오토언박싱으로 자동 처리되지만, 메서드 이름 자체를 알아두면 좋습니다).',
     before:['Integer obj = 100;'], placeholder:['// TODO: obj에서 int 값을 꺼내 num에 저장'],
     after:['System.out.println(num);'],
     expected:'100', answer:['int num = obj.intValue();'],
     note:'int num = obj;로도 자동 언박싱되어 동일하게 동작합니다.',
     regex:[/int\s*num\s*=\s*obj\.intValue\s*\(\s*\)\s*;?/]},

    {id:'PARSE6', level:1, title:'⚠️ 함정: 문자열 덧셈의 연산 순서',
     concept:'+ 연산자는 왼쪽부터 순서대로 계산됩니다. 숫자끼리 먼저 더해진 뒤에 문자열과 합쳐지는지, 아니면 문자열과 먼저 합쳐져 버리는지에 따라 결과가 완전히 달라집니다.',
     before:['int a = 1, b = 2;'], placeholder:['// TODO: "Sum: 3"이 출력되도록, a+b를 먼저 계산해서 문자열에 붙이기'],
     after:[],
     expected:'Sum: 3', answer:['System.out.println("Sum: " + (a + b));'],
     note:'System.out.println("Sum: " + a + b)라고 쓰면 "Sum: " + a가 먼저 문자열로 합쳐져 "Sum: 1"이 되고, 거기에 b가 또 문자열로 이어붙어서 "Sum: 12"라는 의도치 않은 결과가 나옵니다. 괄호로 a+b를 먼저 묶어야 합니다.',
     regex:[/System\.out\.println\s*\(\s*"Sum:\s*"\s*\+\s*\(\s*a\s*\+\s*b\s*\)\s*\)\s*;?/]},

    {id:'STR1', level:2, title:'문자열 길이 구하기',
     concept:'문자열의 글자 수를 알고 싶을 때 쓰는 메서드입니다. 배열의 length 필드와 달리, String은 메서드 호출(괄호)이 필요합니다.',
     before:['String s = "hello";'], placeholder:['// TODO: s의 길이를 len에 저장'],
     after:['System.out.println(len);'],
     expected:'5', answer:['int len = s.length();'],
     note:'배열은 arr.length(필드), 문자열은 s.length()(메서드)라서 괄호 유무가 다릅니다.',
     regex:[/int\s*len\s*=\s*s\.length\s*\(\s*\)\s*;?/]},

    {id:'STR2', level:2, title:'⚠️ 함정: == 대신 equals()로 비교',
     concept:'자바에서 ==는 두 변수가 "같은 객체를 가리키는지"를 비교하고, 문자열의 내용이 같은지는 별도의 메서드로 비교해야 합니다. 특히 new String()으로 만든 문자열은 내용이 같아도 ==가 false를 반환할 수 있습니다.',
     before:['String a = new String("hi");','String b = "hi";'], placeholder:['// TODO: a와 b의 내용이 같은지 비교해 same에 저장'],
     after:['System.out.println(same);'],
     expected:'true', answer:['boolean same = a.equals(b);'],
     note:'a == b는 false입니다 — new String()으로 만든 a는 b와 다른 객체이기 때문입니다. 내용 비교는 항상 equals()를 쓰세요.',
     regex:[/boolean\s*same\s*=\s*a\.equals\s*\(\s*b\s*\)\s*;?/]},

    {id:'STR3', level:2, title:'대소문자 무시 비교',
     concept:'대소문자 차이를 무시하고 내용만 비교하고 싶을 때 쓰는 메서드가 따로 있습니다.',
     before:['String a = "Hello";','String b = "HELLO";'], placeholder:['boolean same = /* TODO */;'],
     after:['System.out.println(same);'],
     expected:'true', answer:['boolean same = a.equalsIgnoreCase(b);'], note:'',
     regex:[/boolean\s*same\s*=\s*a\.equalsIgnoreCase\s*\(\s*b\s*\)\s*;?/]},

    {id:'STR4', level:2, title:'특정 문자열 포함 여부',
     concept:'한 문자열 안에 다른 문자열이 포함되어 있는지 확인하는 메서드가 있습니다.',
     before:['String s = "hello world";'], placeholder:['boolean has = /* TODO */;'],
     after:['System.out.println(has);'],
     expected:'true', answer:['boolean has = s.contains("world");'], note:'',
     regex:[/boolean\s*has\s*=\s*s\.contains\s*\(\s*"world"\s*\)\s*;?/]},

    {id:'STR5', level:2, title:'끝 문자열 확인',
     concept:'문자열이 특정 접미사(suffix)로 끝나는지 확인하는 메서드가 있습니다. 시작 부분을 확인하는 메서드도 짝으로 존재합니다.',
     before:['String s = "hello.txt";'], placeholder:['boolean isTxt = /* TODO */;'],
     after:['System.out.println(isTxt);'],
     expected:'true', answer:['boolean isTxt = s.endsWith(".txt");'], note:'시작 부분 확인은 startsWith()를 사용합니다.',
     regex:[/boolean\s*isTxt\s*=\s*s\.endsWith\s*\(\s*"\.txt"\s*\)\s*;?/]},

    {id:'STR6', level:2, title:'문자열 위치 찾기',
     concept:'특정 부분 문자열이 처음 등장하는 위치(인덱스)를 찾는 메서드가 있습니다. 없으면 -1을 반환합니다.',
     before:['String s = "hello world";'], placeholder:['// TODO: "world"가 시작하는 인덱스를 idx에 저장'],
     after:['System.out.println(idx);'],
     expected:'6', answer:['int idx = s.indexOf("world");'], note:'',
     regex:[/int\s*idx\s*=\s*s\.indexOf\s*\(\s*"world"\s*\)\s*;?/]},

    {id:'STR7', level:2, title:'특정 위치의 문자 가져오기',
     concept:'문자열에서 특정 인덱스의 문자 하나만 꺼내오는 메서드가 있습니다. 반환 타입이 String이 아니라 char라는 점에 주의하세요.',
     before:['String s = "hello";'], placeholder:['// TODO: 인덱스 1의 문자를 ch에 저장 (char)'],
     after:['System.out.println(ch);'],
     expected:'e', answer:['char ch = s.charAt(1);'], note:'',
     regex:[/char\s*ch\s*=\s*s\.charAt\s*\(\s*1\s*\)\s*;?/]},

    {id:'STR8', level:2, title:'사전순 비교',
     concept:'두 문자열의 사전순(lexicographic) 순서를 비교해서, 음수/0/양수로 결과를 알려주는 메서드가 있습니다. 정렬 시 비교자(Comparator)를 직접 만들 때 자주 사용됩니다.',
     before:['String a = "apple";','String b = "banana";'], placeholder:['// TODO: a와 b를 사전순으로 비교해 cmp에 저장 (int)'],
     after:['System.out.println(cmp < 0);'],
     expected:'true', answer:['int cmp = a.compareTo(b);'],
     note:'a가 b보다 사전순으로 앞서면 음수가 반환됩니다.',
     regex:[/int\s*cmp\s*=\s*a\.compareTo\s*\(\s*b\s*\)\s*;?/]},

    {id:'SUB1', level:3, title:'부분 문자열 자르기 (한 인자)',
     concept:'특정 인덱스부터 끝까지 잘라내는 메서드가 있습니다.',
     before:['String s = "hello world";'], placeholder:['// TODO: 인덱스 6부터 끝까지 잘라서 sub에 저장'],
     after:['System.out.println(sub);'],
     expected:'world', answer:['String sub = s.substring(6);'], note:'',
     regex:[/String\s*sub\s*=\s*s\.substring\s*\(\s*6\s*\)\s*;?/]},

    {id:'SUB2', level:3, title:'부분 문자열 자르기 (두 인자)',
     concept:'시작과 끝 인덱스를 둘 다 지정해서 자를 수도 있습니다. 끝 인덱스는 포함되지 않는다는 점에 주의하세요 (배열의 Arrays.fill과 같은 규칙입니다).',
     before:['String s = "hello world";'], placeholder:['// TODO: 인덱스 0부터 5 직전까지 잘라서 sub에 저장'],
     after:['System.out.println(sub);'],
     expected:'hello', answer:['String sub = s.substring(0, 5);'], note:'',
     regex:[/String\s*sub\s*=\s*s\.substring\s*\(\s*0\s*,\s*5\s*\)\s*;?/]},

    {id:'SUB3', level:3, title:'구분자로 분리하기',
     concept:'특정 구분자를 기준으로 문자열을 여러 조각으로 쪼개서 배열로 돌려주는 메서드가 있습니다.',
     before:['String s = "a,b,c";'], placeholder:['// TODO: 쉼표(,) 기준으로 분리해 parts 배열에 저장'],
     after:['System.out.println(parts.length);'],
     expected:'3', answer:['String[] parts = s.split(",");'], note:'',
     regex:[/String\s*\[\s*\]\s*parts\s*=\s*s\.split\s*\(\s*","\s*\)\s*;?/]},

    {id:'SUB4', level:3, title:'문자열 치환',
     concept:'문자열 안의 특정 부분을 다른 문자열로 바꿔주는 메서드가 있습니다. 원본은 바뀌지 않고, 바뀐 결과를 담은 새 문자열이 반환됩니다 — String은 불변(immutable)이라는 걸 기억하세요.',
     before:['String s = "hello world";'], placeholder:['// TODO: "world"를 "java"로 바꿔서 result에 저장'],
     after:['System.out.println(result);'],
     expected:'hello java', answer:['String result = s.replace("world", "java");'], note:'',
     regex:[/String\s*result\s*=\s*s\.replace\s*\(\s*"world"\s*,\s*"java"\s*\)\s*;?/]},

    {id:'SUB5', level:3, title:'양 끝 공백 제거',
     concept:'문자열 양 끝에 붙은 공백을 제거하는 메서드가 있습니다. 사이의 공백은 건드리지 않습니다.',
     before:['String s = "  hi  ";'], placeholder:['// TODO: 양 끝 공백을 제거해 result에 저장'],
     after:['System.out.println("[" + result + "]");'],
     expected:'[hi]', answer:['String result = s.trim();'], note:'',
     regex:[/String\s*result\s*=\s*s\.trim\s*\(\s*\)\s*;?/]},

    {id:'SUB6', level:3, title:'대문자/소문자 변환',
     concept:'문자열 전체를 대문자 또는 소문자로 바꿔주는 메서드가 있습니다.',
     before:['String s = "Hello";'], placeholder:['// TODO: s를 모두 소문자로 바꿔 result에 저장'],
     after:['System.out.println(result);'],
     expected:'hello', answer:['String result = s.toLowerCase();'], note:'',
     regex:[/String\s*result\s*=\s*s\.toLowerCase\s*\(\s*\)\s*;?/]},

    {id:'SUB7', level:3, title:'여러 문자열을 구분자로 합치기',
     concept:'여러 문자열을 정해진 구분자로 이어붙이는 정적 메서드가 있습니다. 반복문 없이 한 줄로 처리할 수 있습니다.',
     before:[], placeholder:['// TODO: "a", "b", "c"를 "-"로 이어붙여 result에 저장'],
     after:['System.out.println(result);'],
     expected:'a-b-c', answer:['String result = String.join("-", "a", "b", "c");'], note:'',
     regex:[/String\s*result\s*=\s*String\.join\s*\(\s*"-"\s*,\s*"a"\s*,\s*"b"\s*,\s*"c"\s*\)\s*;?/]},

    {id:'SUB8', level:3, title:'⚠️ 함정: String은 불변(immutable)',
     concept:'String의 메서드들은 원본을 수정하지 않고, 항상 "새로운 문자열"을 반환합니다. 반환값을 변수에 다시 담지 않으면 변경 사항이 사라집니다.',
     before:['String s = "hello";'], placeholder:['// TODO: s를 대문자로 바꾸고, 그 결과를 다시 s에 저장'],
     after:['System.out.println(s);'],
     expected:'HELLO', answer:['s = s.toUpperCase();'],
     note:'s.toUpperCase();라고만 쓰면 새 문자열이 만들어지기만 하고 어디에도 저장되지 않아서, s는 여전히 "hello"인 채로 남습니다. String이 불변(immutable)이기 때문에 항상 반환값을 받아서 재할당해야 합니다.',
     regex:[/s\s*=\s*s\.toUpperCase\s*\(\s*\)\s*;?/]},

    {id:'EXC1', level:4, title:'기본 try-catch 구조',
     concept:'예외가 발생할 수 있는 코드는 try 블록 안에, 예외가 발생했을 때 실행할 코드는 catch 블록 안에 작성합니다. catch 옆 괄호에는 잡고 싶은 예외 타입을 적습니다.',
     before:['int a = 10, b = 0;','int result;'],
     placeholder:['// TODO: a를 b로 나누되, ArithmeticException이 발생하면 result에 -1 저장'], rows:4,
     after:['System.out.println(result);'],
     expected:'-1',
     answer:['try {','    result = a / b;','} catch (ArithmeticException e) {','    result = -1;','}'],
     note:'정수를 0으로 나누면 ArithmeticException("/ by zero")이 발생합니다. (참고: 0.0으로 나누면 예외 대신 Infinity가 나옵니다 — 정수와 실수의 차이입니다)',
     regex:[/try\s*\{[\s\S]*result\s*=\s*a\s*\/\s*b\s*;[\s\S]*\}\s*catch\s*\(\s*ArithmeticException\s+\w+\s*\)\s*\{[\s\S]*result\s*=\s*-1\s*;[\s\S]*\}/]},

    {id:'EXC2', level:4, title:'finally 블록',
     concept:'try나 catch에서 무슨 일이 일어나든(예외가 나든 안 나든) 항상 마지막에 실행되는 블록이 있습니다. 자원 정리(파일 닫기 등)에 자주 쓰입니다.',
     before:['try {','    int x = 10 / 0;','} catch (ArithmeticException e) {','    System.out.println("error");'],
     placeholder:['// TODO: 위 catch 블록 뒤에, 항상 실행되는 finally 블록을 추가하고 "done" 출력'], rows:3,
     after:[],
     expected:'error, done',
     answer:['} finally {','    System.out.println("done");','}'],
     note:'finally는 catch 블록의 닫는 중괄호 바로 뒤에, 같은 try문의 일부로 이어붙여야 합니다.',
     regex:[/\}\s*finally\s*\{[\s\S]*println\s*\(\s*"done"\s*\)[\s\S]*\}/]},

    {id:'EXC3', level:4, title:'throw로 예외 직접 발생시키기',
     concept:'특정 조건에서 일부러 예외를 발생시키고 싶을 때 쓰는 키워드가 있습니다. new로 예외 객체를 만들어서 던집니다.',
     before:['int age = -5;','try {'],
     placeholder:['    // TODO: age가 음수면 IllegalArgumentException 발생시키기 (메시지: "invalid age")'],
     after:['} catch (IllegalArgumentException e) {','    System.out.println(e.getMessage());','}'],
     expected:'invalid age',
     answer:['if (age < 0) { throw new IllegalArgumentException("invalid age"); }'],
     note:'throw는 예외를 직접 발생시키는 키워드입니다. 메서드 선언부에 붙는 throws와 혼동하지 마세요.',
     regex:[/if\s*\(\s*age\s*<\s*0\s*\)\s*\{?\s*throw\s*new\s*IllegalArgumentException\s*\(\s*"invalid age"\s*\)\s*;?\s*\}?/]},

    {id:'EXC4', level:4, title:'catch 블록 여러 개 (예외 타입별 처리)',
     concept:'서로 다른 종류의 예외를 각각 다르게 처리하고 싶을 때는, catch 블록을 여러 개 나열합니다. 위에서부터 순서대로, 발생한 예외 타입과 일치하는 첫 번째 catch가 실행됩니다.',
     before:['int[] arr = {1, 2, 3};','int idx = 5;'],
     placeholder:['// TODO: arr[idx] 접근을 try로 감싸고, ArrayIndexOutOfBoundsException은 "index error",','//       그 외 Exception은 "other error"로 각각 출력'], rows:5,
     after:[],
     expected:'index error',
     answer:['try {','    int x = arr[idx];','} catch (ArrayIndexOutOfBoundsException e) {','    System.out.println("index error");','} catch (Exception e) {','    System.out.println("other error");','}'],
     note:'catch 블록은 위에서부터 순서대로 검사되므로, 더 구체적인 예외 타입을 먼저, 더 포괄적인 타입(Exception 등)을 나중에 적어야 합니다. 순서가 바뀌면 컴파일 에러가 납니다.',
     regex:[/try\s*\{[\s\S]*arr\s*\[\s*idx\s*\][\s\S]*\}\s*catch\s*\(\s*ArrayIndexOutOfBoundsException\s+\w+\s*\)\s*\{[\s\S]*println\s*\(\s*"index error"\s*\)[\s\S]*\}\s*catch\s*\(\s*Exception\s+\w+\s*\)\s*\{[\s\S]*println\s*\(\s*"other error"\s*\)[\s\S]*\}/]},

    {id:'EXC5', level:4, title:'throws로 떠넘긴 예외, 호출부에서 처리',
     concept:'메서드가 예외를 직접 처리하지 않고 호출한 쪽으로 떠넘기겠다고 선언할 때 throws를 씁니다. 그러면 그 메서드를 호출하는 쪽에서 대신 처리해야 합니다.',
     before:['// parseAge 메서드는 throws NumberFormatException으로 선언되어 있다고 가정','// public static int parseAge(String s) throws NumberFormatException { return Integer.parseInt(s); }','String input = "abc";'],
     placeholder:['// TODO: parseAge(input) 호출을 try로 감싸고, NumberFormatException 발생 시 "invalid number" 출력'], rows:4,
     after:[],
     expected:'invalid number',
     answer:['try {','    int age = parseAge(input);','} catch (NumberFormatException e) {','    System.out.println("invalid number");','}'],
     note:'throws는 메서드가 "이 예외는 내가 처리 안 하고 호출한 쪽에 떠넘긴다"고 선언하는 키워드입니다. throw(예외를 직접 발생시키는 키워드)와 철자가 비슷하니 헷갈리지 마세요.',
     regex:[/try\s*\{[\s\S]*parseAge\s*\(\s*input\s*\)[\s\S]*\}\s*catch\s*\(\s*NumberFormatException\s+\w+\s*\)\s*\{[\s\S]*println\s*\(\s*"invalid number"\s*\)[\s\S]*\}/]},

    {id:'EXC6', level:4, title:'자주 만나는 예외: NullPointerException',
     concept:'null인 객체의 메서드를 호출하려고 하면 발생하는, 코딩테스트에서 정말 자주 마주치는 예외입니다.',
     before:['String s = null;','int len;'],
     placeholder:['// TODO: s.length() 호출을 try로 감싸고, NullPointerException 발생 시 len에 0 저장'], rows:4,
     after:['System.out.println(len);'],
     expected:'0',
     answer:['try {','    len = s.length();','} catch (NullPointerException e) {','    len = 0;','}'],
     note:'null인 객체의 메서드를 호출하면 NullPointerException이 발생합니다. 코딩테스트에서 가장 자주 마주치는 런타임 예외 중 하나입니다.',
     regex:[/try\s*\{[\s\S]*len\s*=\s*s\.length\s*\(\s*\)\s*;[\s\S]*\}\s*catch\s*\(\s*NullPointerException\s+\w+\s*\)\s*\{[\s\S]*len\s*=\s*0\s*;[\s\S]*\}/]},

    {id:'EXC7', level:4, title:'예외 메시지 꺼내기 (getMessage)',
     concept:'catch 블록 안에서, 예외 객체가 들고 있는 메시지를 직접 꺼내볼 수 있는 메서드가 있습니다. 디버깅하거나 사용자에게 보여줄 메시지를 만들 때 유용합니다.',
     before:['try {','    int x = 10 / 0;','} catch (ArithmeticException e) {'],
     placeholder:['    // TODO: 예외 메시지를 출력'],
     after:['}'],
     expected:'/ by zero', answer:['System.out.println(e.getMessage());'], note:'',
     regex:[/System\.out\.println\s*\(\s*e\.getMessage\s*\(\s*\)\s*\)\s*;?/]},

    {id:'CAST2b', level:5, title:'🔁 변형: double → int 캐스팅 (다른 데이터)',
     concept:'더 큰 범위에서 더 작은 범위로 옮길 때는 괄호로 타입을 명시해야 합니다. (CAST2와 같은 패턴, 다른 데이터)',
     before:['double d = 9.7;'], placeholder:['// TODO: d를 int로 캐스팅해서 i에 저장'],
     after:['System.out.println(i);'],
     expected:'9', answer:['int i = (int) d;'], note:'',
     regex:[/int\s*i\s*=\s*\(\s*int\s*\)\s*d\s*;?/]},

    {id:'CAST3b', level:5, title:'🔁 변형: 정수 나눗셈 소수점 살리기 (다른 데이터)',
     concept:'둘 중 하나라도 double로 캐스팅해야 소수점이 살아남습니다. (CAST3과 같은 패턴, 다른 데이터)',
     before:['int a = 9, b = 4;'], placeholder:['// TODO: 정수 나눗셈의 소수점까지 살려서 result에 저장 (double)'],
     after:['System.out.println(result);'],
     expected:'2.25', answer:['double result = (double) a / b;'], note:'',
     regex:[/double\s*result\s*=\s*\(\s*double\s*\)\s*a\s*\/\s*b\s*;?/]},

    {id:'PARSE1b', level:5, title:'🔁 변형: String → int 변환 (다른 데이터)',
     concept:'문자열로 들어온 숫자를 정수로 파싱합니다. (PARSE1과 같은 패턴, 다른 데이터)',
     before:['String str = "777";'], placeholder:['// TODO: str을 정수로 변환해 num에 저장'],
     after:['System.out.println(num + 1);'],
     expected:'778', answer:['int num = Integer.parseInt(str);'], note:'',
     regex:[/int\s*num\s*=\s*Integer\.parseInt\s*\(\s*str\s*\)\s*;?/]},

    {id:'STR2b', level:5, title:'🔁 변형: equals()로 문자열 비교 (다른 데이터)',
     concept:'내용 비교는 ==가 아니라 equals()로 합니다. (STR2와 같은 패턴, 다른 데이터)',
     before:['String a = new String("java");','String b = "java";'], placeholder:['// TODO: a와 b의 내용이 같은지 비교해 same에 저장'],
     after:['System.out.println(same);'],
     expected:'true', answer:['boolean same = a.equals(b);'], note:'',
     regex:[/boolean\s*same\s*=\s*a\.equals\s*\(\s*b\s*\)\s*;?/]},

    {id:'STR6b', level:5, title:'🔁 변형: 문자열 위치 찾기 (다른 데이터)',
     concept:'특정 부분 문자열이 처음 등장하는 인덱스를 찾습니다. (STR6과 같은 패턴, 다른 데이터)',
     before:['String s = "coding test";'], placeholder:['// TODO: "test"가 시작하는 인덱스를 idx에 저장'],
     after:['System.out.println(idx);'],
     expected:'7', answer:['int idx = s.indexOf("test");'], note:'',
     regex:[/int\s*idx\s*=\s*s\.indexOf\s*\(\s*"test"\s*\)\s*;?/]},

    {id:'SUB1b', level:5, title:'🔁 변형: 부분 문자열 자르기 (다른 데이터)',
     concept:'특정 인덱스부터 끝까지 잘라냅니다. (SUB1과 같은 패턴, 다른 데이터)',
     before:['String s = "coding test";'], placeholder:['// TODO: 인덱스 7부터 끝까지 잘라서 sub에 저장'],
     after:['System.out.println(sub);'],
     expected:'test', answer:['String sub = s.substring(7);'], note:'',
     regex:[/String\s*sub\s*=\s*s\.substring\s*\(\s*7\s*\)\s*;?/]},

    {id:'SUB4b', level:5, title:'🔁 변형: 문자열 치환 (다른 데이터)',
     concept:'특정 부분 문자열을 다른 문자열로 바꿉니다. (SUB4와 같은 패턴, 다른 데이터)',
     before:['String s = "coding test";'], placeholder:['// TODO: "test"를 "java"로 바꿔서 result에 저장'],
     after:['System.out.println(result);'],
     expected:'coding java', answer:['String result = s.replace("test", "java");'], note:'',
     regex:[/String\s*result\s*=\s*s\.replace\s*\(\s*"test"\s*,\s*"java"\s*\)\s*;?/]},

    {id:'SUB8b', level:5, title:'🔁 변형: String 불변(immutable) 함정 (다른 데이터)',
     concept:'String 메서드의 반환값은 항상 다시 변수에 담아야 합니다. (SUB8과 같은 패턴, 다른 데이터)',
     before:['String s = "world";'], placeholder:['// TODO: s를 대문자로 바꾸고, 그 결과를 다시 s에 저장'],
     after:['System.out.println(s);'],
     expected:'WORLD', answer:['s = s.toUpperCase();'], note:'',
     regex:[/s\s*=\s*s\.toUpperCase\s*\(\s*\)\s*;?/]},

    {id:'EXC1b', level:5, title:'🔁 변형: try-catch로 ArithmeticException 처리 (다른 데이터)',
     concept:'0으로 나누면 발생하는 ArithmeticException을 try-catch로 처리합니다. (EXC1과 같은 패턴, 다른 데이터)',
     before:['int a = 20, b = 0;','int result;'],
     placeholder:['// TODO: a를 b로 나누되, ArithmeticException이 발생하면 result에 -1 저장'], rows:4,
     after:['System.out.println(result);'],
     expected:'-1',
     answer:['try {','    result = a / b;','} catch (ArithmeticException e) {','    result = -1;','}'], note:'',
     regex:[/try\s*\{[\s\S]*result\s*=\s*a\s*\/\s*b\s*;[\s\S]*\}\s*catch\s*\(\s*ArithmeticException\s+\w+\s*\)\s*\{[\s\S]*result\s*=\s*-1\s*;[\s\S]*\}/]},

    {id:'EXC6b', level:5, title:'🔁 변형: NullPointerException 처리 (다른 데이터)',
     concept:'null인 객체의 메서드 호출을 try-catch로 처리합니다. (EXC6과 같은 패턴, 다른 데이터)',
     before:['String s = null;','int len;'],
     placeholder:['// TODO: s.length() 호출을 try로 감싸고, NullPointerException 발생 시 len에 -1 저장'], rows:4,
     after:['System.out.println(len);'],
     expected:'-1',
     answer:['try {','    len = s.length();','} catch (NullPointerException e) {','    len = -1;','}'], note:'',
     regex:[/try\s*\{[\s\S]*len\s*=\s*s\.length\s*\(\s*\)\s*;[\s\S]*\}\s*catch\s*\(\s*NullPointerException\s+\w+\s*\)\s*\{[\s\S]*len\s*=\s*-1\s*;[\s\S]*\}/]},

    {id:'CTRL1', level:6, title:'for문 — 1부터 5까지 합계',
     concept:'for문은 (초기화; 조건; 증감) 세 부분으로 반복 횟수를 제어합니다. 코테에서 배열 순회·누적·카운팅 등 거의 모든 반복에 씁니다.',
     before:['int sum = 0;'], placeholder:['// TODO: for문으로 1~5를 sum에 누적'],
     after:['System.out.println(sum);'],
     expected:'15', answer:['for (int i = 1; i <= 5; i++) sum += i;'], note:'',
     regex:[/for\s*\(\s*int\s+i\s*=\s*1\s*;\s*i\s*<=\s*5\s*;/, /sum\s*\+=\s*i\s*;?/]},

    {id:'CTRL2', level:6, title:'향상된 for문 (for-each) — 배열 순회',
     concept:'배열·컬렉션의 원소를 처음부터 끝까지 꺼낼 때 인덱스 없이 쓸 수 있는 문법입니다. 인덱스가 필요 없는 순회에는 이쪽이 더 읽기 좋습니다.',
     before:['int[] nums = {2, 4, 6};', 'int sum = 0;'],
     placeholder:['// TODO: for-each로 nums를 순회해 sum에 누적'],
     after:['System.out.println(sum);'],
     expected:'12', answer:['for (int n : nums) sum += n;'], note:'',
     regex:[/for\s*\(\s*int\s+\w+\s*:\s*nums\s*\)/, /sum\s*\+=\s*\w+\s*;?/]},

    {id:'CTRL3', level:6, title:'while + break — 조건 탈출 패턴',
     concept:'while은 조건이 true인 동안 반복하며, break를 만나면 즉시 루프를 탈출합니다. 종료 조건을 미리 알기 어렵거나 특정 값을 찾으면 멈추는 탐색 로직에 씁니다.',
     before:['int[] arr = {-3, -1, 4, 2};', 'int result = -1;', 'int i = 0;'],
     placeholder:['// TODO: arr에서 첫 번째 양수를 result에 저장하고 break'],
     after:['System.out.println(result);'],
     expected:'4', answer:['while (i < arr.length) {', '    if (arr[i] > 0) { result = arr[i]; break; }', '    i++;', '}'],
     note:'break 없이 계속 돌면 마지막 양수 2가 result에 덮어씌워집니다.',
     regex:[/while\s*\(\s*i\s*<\s*arr\.length\s*\)/, /result\s*=\s*arr\s*\[\s*i\s*\]/, /break\s*;/]},

    {id:'MATH1', level:6, title:'Math.max — 두 값 중 더 큰 값',
     concept:'두 값을 비교해 더 큰 쪽을 반환합니다. if문 없이 최댓값을 한 줄로 구할 수 있어 코테에서 자주 씁니다.',
     before:['int a = 7, b = 3;'], placeholder:['// TODO: a와 b 중 큰 값을 max에 저장'],
     after:['System.out.println(max);'],
     expected:'7', answer:['int max = Math.max(a, b);'], note:'',
     regex:[/int\s+max\s*=\s*Math\.max\s*\(\s*a\s*,\s*b\s*\)\s*;?/]},

    {id:'MATH2', level:6, title:'Math.min — 두 값 중 더 작은 값',
     concept:'두 값을 비교해 더 작은 쪽을 반환합니다. Math.max와 함께 범위 클램핑·경계 처리에 많이 씁니다.',
     before:['int a = 7, b = 3;'], placeholder:['// TODO: a와 b 중 작은 값을 min에 저장'],
     after:['System.out.println(min);'],
     expected:'3', answer:['int min = Math.min(a, b);'], note:'',
     regex:[/int\s+min\s*=\s*Math\.min\s*\(\s*a\s*,\s*b\s*\)\s*;?/]},

    {id:'MATH3', level:6, title:'Math.abs — 절댓값',
     concept:'음수를 양수로 바꿔 절댓값을 반환합니다. 두 값의 차이·거리 계산 시 부호에 관계없이 크기만 구할 때 씁니다.',
     before:['int n = -5;'], placeholder:['// TODO: n의 절댓값을 abs에 저장'],
     after:['System.out.println(abs);'],
     expected:'5', answer:['int abs = Math.abs(n);'], note:'',
     regex:[/int\s+abs\s*=\s*Math\.abs\s*\(\s*n\s*\)\s*;?/]},

    {id:'CONST1', level:6, title:'Integer.MAX_VALUE — 최솟값 초기화 패턴',
     concept:'배열에서 최솟값을 찾을 때 비교 기준 초기값으로 Integer.MAX_VALUE를 씁니다. 어떤 값과 첫 번째로 비교해도 반드시 갱신되어 올바른 최솟값이 남습니다.',
     before:['int[] arr = {3, 1, 4, 1, 5};'],
     placeholder:['// TODO: min을 Integer.MAX_VALUE로 초기화하고, for-each로 실제 최솟값을 구하기'],
     after:['System.out.println(min);'], rows:3,
     expected:'1', answer:['int min = Integer.MAX_VALUE;', 'for (int v : arr) if (v < min) min = v;'],
     note:'최댓값을 찾을 때는 반대로 Integer.MIN_VALUE로 초기화합니다.',
     regex:[/Integer\.MAX_VALUE/, /for\s*\(/, /min\s*=\s*\w+|Math\.min\s*\(\s*min/]},

    {id:'TERN1', level:6, title:'삼항 연산자 — 조건 ? 참값 : 거짓값',
     concept:'if-else를 한 줄 표현식으로 줄입니다. 조건이 true이면 ? 뒤의 값, false이면 : 뒤의 값을 반환합니다. 변수 초기화와 동시에 분기할 때 깔끔합니다.',
     before:['int n = 7;'], placeholder:['// TODO: n이 짝수면 "even", 홀수면 "odd"를 result에 저장 (삼항 연산자)'],
     after:['System.out.println(result);'],
     expected:'odd', answer:['String result = (n % 2 == 0) ? "even" : "odd";'], note:'',
     regex:[/String\s+result\s*=/, /\?\s*"even"\s*:\s*"odd"|n\s*%\s*2\s*!=\s*0.*\?\s*"odd"/]}

  ];
