window.QUESTIONS = [
    {id:'LM1', level:0, title:'함수형 인터페이스와 람다 기본 문법',
     concept:'추상 메서드가 딱 하나뿐인 인터페이스를 함수형 인터페이스(functional interface)라고 합니다. 이런 인터페이스는 (매개변수) -> 본문 형태의 람다식으로 간단하게 구현체를 만들 수 있습니다.',
     before:['interface Greeting {','    void say(String name);','}'],
     placeholder:['// TODO: name을 받아 "안녕 " + name을 출력하는 람다로 Greeting 객체 greeting 만들기'], rows:3,
     after:['greeting.say("철수");'],
     expected:'안녕 철수',
     answer:['Greeting greeting = (name) -> System.out.println("안녕 " + name);'],
     note:'매개변수가 하나뿐이면 괄호를 생략하고 name -> ... 처럼 쓸 수도 있습니다.',
     regex:[/Greeting\s+greeting\s*=\s*\(?\s*name\s*\)?\s*->\s*System\.out\.println\s*\(\s*"안녕\s*"\s*\+\s*name\s*\)/]},
    {id:'LM2', level:0, title:'Runnable과 람다',
     concept:'java.lang.Runnable은 매개변수도 반환값도 없는 run() 메서드 하나만 가진 대표적인 함수형 인터페이스입니다. 람다로 구현하면 () -> 본문 형태가 됩니다.',
     before:[],
     placeholder:['Runnable task = /* TODO */;'],
     after:['task.run();'],
     expected:'실행 중!',
     answer:['Runnable task = () -> System.out.println("실행 중!");'], note:'',
     regex:[/Runnable\s+task\s*=\s*\(\s*\)\s*->\s*System\.out\.println\s*\(\s*"실행\s*중!"\s*\)/]},
    {id:'LM3', level:0, title:'Comparator를 람다로 작성',
     concept:'Comparator<T>도 compare(T a, T b) 메서드 하나뿐인 함수형 인터페이스라서 람다로 간단히 쓸 수 있습니다. 정수를 오름차순으로 정렬하려면 a - b를 반환하면 됩니다.',
     before:['List<Integer> list = new ArrayList<>(Arrays.asList(5, 1, 3));'],
     placeholder:['// TODO: 오름차순 정렬을 위한 람다 Comparator로 list 정렬'],
     after:['System.out.println(list);'],
     expected:'[1, 3, 5]',
     answer:['Collections.sort(list, (a, b) -> a - b);'], note:'',
     regex:[/Collections\.sort\s*\(\s*list\s*,\s*\(\s*a\s*,\s*b\s*\)\s*->\s*a\s*-\s*b\s*\)/]},
    {id:'LM4', level:0, title:'Predicate<T> — 참/거짓 판단',
     concept:'Predicate<T>는 값을 하나 받아서 boolean을 반환하는 함수형 인터페이스입니다. test(T t) 메서드 하나를 람다로 구현해서 "이 값이 조건을 만족하는가"를 표현합니다.',
     before:[],
     placeholder:['Predicate<Integer> isEven = /* TODO */;'],
     after:['System.out.println(isEven.test(4));','System.out.println(isEven.test(5));'],
     expected:'true, false',
     answer:['Predicate<Integer> isEven = (n) -> n % 2 == 0;'],
     note:'java.util.function 패키지에는 Predicate, Function, Consumer, Supplier 같은 미리 만들어진 함수형 인터페이스가 있어서, 매번 새 인터페이스를 직접 정의하지 않아도 됩니다.',
     regex:[/Predicate\s*<\s*Integer\s*>\s*isEven\s*=\s*\(?\s*n\s*\)?\s*->\s*n\s*%\s*2\s*==\s*0/]},
    {id:'LM5', level:0, title:'Function<T,R> — 값을 변환',
     concept:'Function<T, R>은 T 타입 값을 받아 R 타입 값으로 변환해서 반환하는 함수형 인터페이스입니다. apply(T t) 메서드를 람다로 구현합니다.',
     before:[],
     placeholder:['Function<Integer, Integer> square = /* TODO */;'],
     after:['System.out.println(square.apply(5));'],
     expected:'25',
     answer:['Function<Integer, Integer> square = (n) -> n * n;'], note:'',
     regex:[/Function\s*<\s*Integer\s*,\s*Integer\s*>\s*square\s*=\s*\(?\s*n\s*\)?\s*->\s*n\s*\*\s*n/]},
    {id:'LM6', level:0, title:'Consumer<T> — 값을 받아 소비',
     concept:'Consumer<T>는 값을 하나 받아서 처리만 하고 아무것도 반환하지 않는 함수형 인터페이스입니다. accept(T t) 메서드를 람다로 구현합니다.',
     before:[],
     placeholder:['Consumer<String> printer = /* TODO */;'],
     after:['printer.accept("데이터");'],
     expected:'받음: 데이터',
     answer:['Consumer<String> printer = (s) -> System.out.println("받음: " + s);'], note:'',
     regex:[/Consumer\s*<\s*String\s*>\s*printer\s*=\s*\(?\s*s\s*\)?\s*->\s*System\.out\.println\s*\(\s*"받음:\s*"\s*\+\s*s\s*\)/]},
    {id:'LM7', level:0, title:'메서드 레퍼런스(Method Reference)',
     concept:'람다가 단순히 이미 있는 메서드 하나를 그대로 호출만 하는 형태일 때는, 클래스명::메서드명으로 더 짧게 줄여 쓸 수 있습니다. 이를 메서드 레퍼런스라고 합니다.',
     before:['List<String> names = Arrays.asList("banana", "apple", "cherry");'],
     placeholder:['// TODO: 메서드 레퍼런스(System.out::println)로 각 이름 출력'],
     after:[],
     expected:'banana, apple, cherry',
     answer:['names.forEach(System.out::println);'],
     note:'(s) -> System.out.println(s) 와 완전히 같은 동작이지만 더 간결합니다.',
     regex:[/names\.forEach\s*\(\s*System\.out::println\s*\)/]},

    /* ---------------- 6장 Stream API 기초 ---------------- */,
    {id:'SM1', level:1, title:'stream() + filter() + forEach()',
     concept:'컬렉션에서 .stream()을 호출하면 데이터를 가공하는 파이프라인을 시작할 수 있습니다. filter()는 조건을 만족하는 원소만 남기고, forEach()는 각 원소에 대해 동작을 실행합니다.',
     before:['List<Integer> nums = Arrays.asList(1, 2, 3, 4, 5, 6);'],
     placeholder:['// TODO: stream으로 짝수만 걸러서 출력'], rows:3,
     after:[],
     expected:'2, 4, 6',
     answer:['nums.stream().filter(n -> n % 2 == 0).forEach(System.out::println);'], note:'',
     regex:[/nums\.stream\s*\(\s*\)/, /filter\s*\(\s*\w+\s*->\s*\w+\s*%\s*2\s*==\s*0\s*\)/, /forEach\s*\(/]},
    {id:'SM2', level:1, title:'map()으로 변환',
     concept:'map()은 스트림의 각 원소를 다른 값으로 하나씩 변환합니다. 원소 개수는 그대로 유지되고, 값만 바뀝니다.',
     before:['List<Integer> nums = Arrays.asList(1, 2, 3);'],
     placeholder:['// TODO: 각 원소를 제곱한 뒤 출력'], rows:3,
     after:[],
     expected:'1, 4, 9',
     answer:['nums.stream().map(n -> n * n).forEach(System.out::println);'], note:'',
     regex:[/nums\.stream\s*\(\s*\)/, /map\s*\(\s*\w+\s*->\s*\w+\s*\*\s*\w+\s*\)/, /forEach\s*\(/]},
    {id:'SM3', level:1, title:'collect(Collectors.toList())로 다시 리스트로',
     concept:'filter나 map을 거친 스트림은 그 자체로는 List가 아닙니다. 다시 리스트로 모으려면 collect(Collectors.toList())를 마지막에 붙여야 합니다.',
     before:['List<Integer> nums = Arrays.asList(1, 2, 3, 4, 5);'],
     placeholder:['// TODO: 3보다 큰 값만 걸러서 List<Integer> result로 모으기'], rows:3,
     after:['System.out.println(result);'],
     expected:'[4, 5]',
     answer:['List<Integer> result = nums.stream().filter(n -> n > 3).collect(Collectors.toList());'], note:'',
     regex:[/List\s*<\s*Integer\s*>\s*result\s*=\s*nums\.stream\s*\(\s*\)/, /filter\s*\(\s*\w+\s*->\s*\w+\s*>\s*3\s*\)/, /collect\s*\(\s*Collectors\.toList\s*\(\s*\)\s*\)/]},
    {id:'SM4', level:1, title:'count()로 개수 세기',
     concept:'스트림을 거친 뒤 남은 원소 개수만 알고 싶다면, 리스트로 모을 필요 없이 count()를 바로 호출하면 됩니다. 반환 타입은 long입니다.',
     before:['List<Integer> nums = Arrays.asList(1, 2, 3, 4, 5, 6, 7);'],
     placeholder:['// TODO: 짝수 개수를 세어 cnt에 저장'], rows:3,
     after:['System.out.println(cnt);'],
     expected:'3',
     answer:['long cnt = nums.stream().filter(n -> n % 2 == 0).count();'], note:'',
     regex:[/long\s+cnt\s*=\s*nums\.stream\s*\(\s*\)/, /filter\s*\(\s*\w+\s*->\s*\w+\s*%\s*2\s*==\s*0\s*\)/, /\.count\s*\(\s*\)/]},
    {id:'SM5', level:1, title:'sorted()로 정렬',
     concept:'sorted()는 스트림의 원소를 정렬합니다. 인자 없이 호출하면 자연 순서(오름차순)로, Comparator를 넘기면 그 기준으로 정렬됩니다.',
     before:['List<Integer> nums = Arrays.asList(5, 1, 4, 2, 3);'],
     placeholder:['// TODO: 오름차순 정렬한 뒤 출력'], rows:3,
     after:[],
     expected:'1, 2, 3, 4, 5',
     answer:['nums.stream().sorted().forEach(System.out::println);'], note:'',
     regex:[/nums\.stream\s*\(\s*\)/, /\.sorted\s*\(\s*\)/, /forEach\s*\(/]},
    {id:'SM6', level:1, title:'reduce()로 누적 계산',
     concept:'reduce()는 스트림의 모든 원소를 하나의 값으로 누적해서 합칩니다. 초깃값과, 누적된 값과 다음 원소를 어떻게 합칠지를 정의하는 람다를 함께 넘겨줍니다.',
     before:['List<Integer> nums = Arrays.asList(1, 2, 3, 4);'],
     placeholder:['// TODO: reduce로 모든 원소의 합을 sum에 저장 (초깃값 0)'], rows:3,
     after:['System.out.println(sum);'],
     expected:'10',
     answer:['int sum = nums.stream().reduce(0, (a, b) -> a + b);'], note:'',
     regex:[/int\s+sum\s*=\s*nums\.stream\s*\(\s*\)/, /reduce\s*\(\s*0\s*,\s*\(\s*a\s*,\s*b\s*\)\s*->\s*a\s*\+\s*b\s*\)/]},
    {id:'SM7', level:1, title:'mapToInt + sum()으로 합계',
     concept:'Stream<Integer>를 기본형 스트림인 IntStream으로 바꾸면, sum()처럼 숫자 전용 집계 메서드를 바로 쓸 수 있습니다. mapToInt()로 변환합니다.',
     before:['List<Integer> nums = Arrays.asList(1, 2, 3, 4, 5);'],
     placeholder:['// TODO: mapToInt로 변환 후 sum()으로 합계를 total에 저장'], rows:3,
     after:['System.out.println(total);'],
     expected:'15',
     answer:['int total = nums.stream().mapToInt(n -> n).sum();'],
     note:'reduce(0, (a,b)->a+b)와 같은 결과지만, 숫자 합계만 구할 땐 mapToInt().sum()이 더 짧고 의도도 명확합니다.',
     regex:[/nums\.stream\s*\(\s*\)\.mapToInt\s*\(/, /\.sum\s*\(\s*\)/]},
    {id:'SM8', level:1, title:'Collectors.joining()으로 문자열 합치기',
     concept:'문자열 스트림을 구분자로 이어붙여 하나의 문자열로 만들고 싶다면 collect(Collectors.joining(구분자))를 씁니다.',
     before:['List<String> names = Arrays.asList("철수", "영희", "민수");'],
     placeholder:['// TODO: ", "로 구분해서 하나의 문자열로 합쳐 result에 저장'], rows:3,
     after:['System.out.println(result);'],
     expected:'철수, 영희, 민수',
     answer:['String result = names.stream().collect(Collectors.joining(", "));'], note:'',
     regex:[/String\s+result\s*=\s*names\.stream\s*\(\s*\)/, /Collectors\.joining\s*\(\s*",\s*"\s*\)/]},

    /* ---------------- 7장 변형 연습 ---------------- */,
    {id:'V5', level:3, title:'🔁 변형: 람다 Comparator (내림차순)',
     concept:'LM3과 같은 람다 Comparator 패턴이지만, 이번엔 내림차순입니다.',
     before:['List<Integer> list = new ArrayList<>(Arrays.asList(5, 1, 3));'],
     placeholder:['// TODO: 내림차순 정렬을 위한 람다 Comparator로 list 정렬'],
     after:['System.out.println(list);'],
     expected:'[5, 3, 1]',
     answer:['Collections.sort(list, (a, b) -> b - a);'], note:'',
     regex:[/Collections\.sort\s*\(\s*list\s*,\s*\(\s*a\s*,\s*b\s*\)\s*->\s*b\s*-\s*a\s*\)/]},
    {id:'V6', level:3, title:'🔁 변형: Predicate (다른 조건)',
     concept:'LM4와 같은 Predicate 패턴이지만, 이번엔 양수 판별입니다.',
     before:[],
     placeholder:['Predicate<Integer> isPositive = /* TODO */;'],
     after:['System.out.println(isPositive.test(3));','System.out.println(isPositive.test(-2));'],
     expected:'true, false',
     answer:['Predicate<Integer> isPositive = (n) -> n > 0;'], note:'',
     regex:[/Predicate\s*<\s*Integer\s*>\s*isPositive\s*=\s*\(?\s*n\s*\)?\s*->\s*n\s*>\s*0/]},
    {id:'V7', level:3, title:'🔁 변형: Stream filter+map 조합',
     concept:'SM1, SM2와 같은 stream 패턴을 한 번에 연결한 변형입니다 — filter로 거르고 map으로 변환한 뒤 출력합니다.',
     before:['List<Integer> nums = Arrays.asList(1, 2, 3, 4, 5, 6);'],
     placeholder:['// TODO: 짝수만 걸러서 각각 10을 곱한 뒤 출력'], rows:3,
     after:[],
     expected:'20, 40, 60',
     answer:['nums.stream().filter(n -> n % 2 == 0).map(n -> n * 10).forEach(System.out::println);'], note:'',
     regex:[/nums\.stream\s*\(\s*\)/, /filter\s*\(\s*\w+\s*->\s*\w+\s*%\s*2\s*==\s*0\s*\)/, /map\s*\(\s*\w+\s*->\s*\w+\s*\*\s*10\s*\)/, /forEach\s*\(/]},
    {id:'V8', level:3, title:'🔁 변형: Stream collect (다른 조건)',
     concept:'SM3과 같은 collect(Collectors.toList()) 패턴이지만, 이번엔 조건과 데이터가 다릅니다.',
     before:['List<Integer> nums = Arrays.asList(10, 20, 30, 40, 50);'],
     placeholder:['// TODO: 25보다 작은 값만 걸러서 List<Integer> result로 모으기'], rows:3,
     after:['System.out.println(result);'],
     expected:'[10, 20]',
     answer:['List<Integer> result = nums.stream().filter(n -> n < 25).collect(Collectors.toList());'], note:'',
     regex:[/List\s*<\s*Integer\s*>\s*result\s*=\s*nums\.stream\s*\(\s*\)/, /filter\s*\(\s*\w+\s*->\s*\w+\s*<\s*25\s*\)/, /collect\s*\(\s*Collectors\.toList\s*\(\s*\)\s*\)/]},
    {id:'IO1', level:2, title:'입출력: Scanner로 정수 입력받기',
     concept:'Scanner는 표준 입력(standard input)을 토큰(공백·줄바꿈 기준) 단위로 끊어 읽습니다. 그중에서 정수 하나만 읽어오는 메서드가 있습니다.',
     before:['// 입력: "5" 한 줄이 들어온다고 가정','Scanner sc = new Scanner(System.in);'],
     placeholder:['// TODO: 정수 하나를 입력받아 n에 저장'],
     after:['System.out.println(n);'],
     expected:'5', answer:['int n = sc.nextInt();'], note:'',
     regex:[/int\s*n\s*=\s*sc\.nextInt\s*\(\s*\)\s*;?/]},
    {id:'IO2', level:2, title:'입출력: Scanner로 문자열 한 줄 입력받기',
     concept:'nextInt()나 next()는 공백을 기준으로 한 토큰만 읽습니다. 공백이 포함된 한 줄 전체를 통째로 읽고 싶을 때 쓰는 메서드가 따로 있습니다.',
     before:['// 입력: "hello world" 한 줄이 들어온다고 가정','Scanner sc = new Scanner(System.in);'],
     placeholder:['// TODO: 한 줄 전체를 line에 저장'],
     after:['System.out.println(line);'],
     expected:'hello world', answer:['String line = sc.nextLine();'], note:'',
     regex:[/String\s*line\s*=\s*sc\.nextLine\s*\(\s*\)\s*;?/]},
    {id:'IO3', level:2, title:'입출력: ⚠️ 함정 — nextInt() 뒤의 nextLine()',
     concept:'nextInt()는 숫자만 읽고, 그 줄 끝의 줄바꿈 문자는 입력 버퍼에 그대로 남겨둡니다. 바로 다음에 nextLine()을 호출하면 새 줄이 아니라 버퍼에 남아있던 그 줄바꿈 문자만 읽혀서 빈 문자열이 반환됩니다. 코딩테스트에서 정수와 문자열 입력을 섞어 받을 때 가장 많이 걸리는 함정이니, 어떻게 해결해야 할지 생각해보세요.',
     before:['// 입력: "3" 그리고 다음 줄에 "hello" 가 들어온다고 가정','Scanner sc = new Scanner(System.in);','int num = sc.nextInt();'],
     placeholder:['// TODO: 버퍼에 남은 줄바꿈을 먼저 버리고, 다음 줄을 line에 저장'], rows:3,
     after:['System.out.println(line);'],
     expected:'hello', answer:['sc.nextLine();','String line = sc.nextLine();'],
     note:'첫 번째 nextLine()이 nextInt() 뒤에 남은 줄바꿈 문자를 소비(consume)하는 역할을 합니다. 이 줄이 빠지면 line에 빈 문자열("")이 들어가는 게 바로 이 문제의 함정입니다.',
     regex:[/sc\.nextLine\s*\(\s*\)\s*;[\s\S]*String\s*line\s*=\s*sc\.nextLine\s*\(\s*\)\s*;?/]},
    {id:'IO4', level:2, title:'입출력: BufferedReader로 한 줄 읽기',
     concept:'Scanner는 입력을 파싱(parsing)하는 과정 때문에 비교적 느립니다. 입력 줄 수가 많은 코딩테스트에서는, 버퍼링된 스트림으로 한 줄을 통째로 빠르게 읽어오는 방법을 더 선호합니다. System.in을 감싸는 두 단계를 거쳐야 합니다.',
     before:['// 입력: "hello" 한 줄이 들어온다고 가정','BufferedReader br = new BufferedReader(new InputStreamReader(System.in));'],
     placeholder:['// TODO: 한 줄을 읽어 line에 저장'],
     after:['System.out.println(line);'],
     expected:'hello', answer:['String line = br.readLine();'],
     note:'readLine()은 IOException을 던질 수 있어서, 보통 메서드 선언에 throws IOException을 추가해 처리합니다. (이 채점기는 throws 여부까지는 검사하지 않습니다.)',
     regex:[/String\s*line\s*=\s*br\.readLine\s*\(\s*\)\s*;?/]},
    {id:'IO5', level:2, title:'입출력: StringTokenizer로 토큰 분리',
     concept:'한 줄에 공백으로 구분된 값이 여러 개 들어올 때, 이를 토큰(token) 단위로 하나씩 잘라주는 클래스가 있습니다. 생성자에 원본 문자열을 넘기면, 호출할 때마다 다음 토큰을 하나씩 돌려줍니다.',
     before:['// 입력: "3 5 7" 한 줄이 들어온다고 가정','String line = "3 5 7";'],
     placeholder:['// TODO: line을 공백 기준으로 분리하는 StringTokenizer st 생성'],
     after:['System.out.println(st.nextToken());','System.out.println(st.nextToken());','System.out.println(st.nextToken());'],
     expected:'3, 5, 7', answer:['StringTokenizer st = new StringTokenizer(line);'], note:'',
     regex:[/StringTokenizer\s*st\s*=\s*new\s*StringTokenizer\s*\(\s*line\s*\)\s*;?/]},
    {id:'IO6', level:2, title:'입출력: BufferedReader + StringTokenizer 조합',
     concept:'BufferedReader로 빠르게 한 줄을 읽고, 그 줄을 StringTokenizer로 토큰 단위로 쪼개는 조합은 코딩테스트에서 가장 흔한 입력 처리 패턴입니다. 단, StringTokenizer가 돌려주는 토큰은 항상 String이라는 점에 주의하세요 — 숫자로 쓰려면 한 단계를 더 거쳐야 합니다.',
     before:['// 입력: "10 20" 한 줄이 들어온다고 가정','BufferedReader br = new BufferedReader(new InputStreamReader(System.in));','StringTokenizer st = new StringTokenizer(br.readLine());'],
     placeholder:['int a = /* TODO */;','int b = /* TODO */;'], rows:3,
     after:['System.out.println(a + b);'],
     expected:'30',
     answer:['int a = Integer.parseInt(st.nextToken());','int b = Integer.parseInt(st.nextToken());'],
     note:'StringTokenizer가 돌려주는 토큰은 항상 String이므로, 숫자로 쓰려면 Integer.parseInt()로 직접 변환해야 합니다.',
     regex:[/int\s*a\s*=\s*Integer\.parseInt\s*\(\s*st\.nextToken\s*\(\s*\)\s*\)\s*;?/, /int\s*b\s*=\s*Integer\.parseInt\s*\(\s*st\.nextToken\s*\(\s*\)\s*\)\s*;?/]},
    {id:'IO7', level:2, title:'입출력: StringBuilder로 문자열 누적',
     concept:'반복문 안에서 String을 +=로 계속 이어붙이면, 그때마다 새로운 String 객체가 만들어져서 데이터가 많아질수록 점점 느려집니다. 내부 버퍼를 직접 수정(mutate)해서 훨씬 빠르게 문자열을 이어붙이는 클래스가 있습니다.',
     before:['StringBuilder sb = new StringBuilder();','for (int i = 1; i <= 3; i++) {'],
     placeholder:['    // TODO: sb에 i를 추가'],
     after:['}','System.out.println(sb.toString());'],
     expected:'123', answer:['sb.append(i);'],
     note:'String을 +=로 반복 이어붙이면 매번 새 String 객체가 생성되어 느려집니다(대략 O(n²)). StringBuilder.append()는 내부 버퍼를 직접 수정해서 훨씬 빠릅니다.',
     regex:[/sb\.append\s*\(\s*i\s*\)\s*;?/]},
  {id:'IO8', level:2, title:'입출력: StringBuilder로 줄바꿈 포함 출력',
   concept:'여러 줄을 출력할 때 StringBuilder에 값과 줄바꿈(\\n)을 함께 append()하면 효율적입니다.',
   before:['StringBuilder sb = new StringBuilder();','String[] words = {"apple", "banana", "cherry"};','for (String w : words) {'],
   placeholder:['    // TODO: sb에 w와 줄바꿈(\\n)을 함께 추가'],
   after:['}','System.out.print(sb);'],
   expected:'apple\\nbanana\\ncherry\\n',
   answer:['sb.append(w).append("\\n");'],
   note:'append()는 자기 자신을 반환하므로 메서드 체이닝이 가능합니다.',
   regex:[/sb\.append\s*\(\s*w\s*\).*\.append\s*\(\s*"\\n"\s*\)\s*;?/]}
];
