window.CHAPTER_DATA = window.CHAPTER_DATA || {};
window.CHAPTER_DATA[4] = window.CHAPTER_DATA[4] || {};
window.CHAPTER_DATA[4].questions = [
    /* ---------------- 1장 Stack ---------------- */
    {id:'ST1', level:0, title:'Stack 기본 — push & pop',
     concept:'값을 순서대로 쌓아올리는 연산과, 맨 위 값을 꺼내면서 동시에 제거하는 연산이 짝을 이룹니다. 꺼낸 값은 변수에 담아 출력에 사용해야 합니다.',
     before:['Deque<Integer> stack = new ArrayDeque<>();'],
     placeholder:['// TODO','// (1, 2, 3 순서로 push 한 뒤, 맨 위 값을 꺼내 top에 저장)'], rows:4,
     after:['System.out.println(top);','System.out.println(stack);'],
     expected:'3, [2, 1]',
     answer:['stack.push(1);','stack.push(2);','stack.push(3);','int top = stack.pop();'],
     note:'ArrayDeque를 스택처럼 쓸 때 push()/pop()은 모두 앞쪽을 기준으로 동작합니다. 그래서 toString()으로 출력하면 가장 나중에 넣은 값이 맨 앞에 나옵니다.',
     regex:[/push\s*\(\s*1\s*\)/, /push\s*\(\s*2\s*\)/, /push\s*\(\s*3\s*\)/, /int\s+top\s*=\s*stack\.pop\s*\(\s*\)/]},

    {id:'ST2', level:0, title:'peek() — top 값 확인',
     concept:'스택에서 가장 위에 있는 값을 제거하지 않고 확인만 하는 연산입니다. 여러 번 호출해도 스택 상태는 그대로 유지됩니다.',
     before:['Deque<Integer> stack = new ArrayDeque<>();','stack.push(10);','stack.push(20);','stack.push(30);'],
     placeholder:['int top = /* TODO */;'],
     after:['System.out.println(top);','System.out.println(stack.size());'],
     expected:'30, 3',
     answer:['int top = stack.peek();'], note:'',
     regex:[/int\s+top\s*=\s*stack\.peek\s*\(\s*\)/]},

    {id:'ST3', level:0, title:'괄호 짝 검사',
     concept:'여는 괄호를 만나면 쌓아두고, 닫는 괄호를 만나면 하나를 꺼내 짝을 맞춥니다. 문자열을 모두 처리한 뒤 스택이 비어있으면 짝이 맞는 것입니다.',
     before:['String s = "((()))";','Deque<Character> stack = new ArrayDeque<>();'],
     placeholder:['// TODO','// (\'(\'를 만나면 push, \')\'를 만나면 pop)'], rows:4,
     after:['System.out.println(stack.isEmpty());'],
     expected:'true',
     answer:['for (char c : s.toCharArray()) {','    if (c == \'(\') stack.push(c);','    else stack.pop();','}'],
     note:'이 문제는 괄호 한 종류만 다루는 단순화 버전입니다. 실전에서는 여는/닫는 괄호의 종류까지 짝이 맞는지 검사해야 합니다.',
     regex:[/for\s*\(\s*char\s+\w+\s*:\s*s\.toCharArray\s*\(\s*\)\s*\)/, /stack\.push\s*\(/, /stack\.pop\s*\(\s*\)/]},

    {id:'ST4', level:0, title:'후위표기법(postfix) 계산',
     concept:'후위표기법은 연산자가 피연산자 뒤에 옵니다. 숫자를 만나면 push하고, 연산자를 만나면 두 번 pop해서 계산한 뒤 다시 push합니다. 먼저 꺼낸 값이 오른쪽, 다음에 꺼낸 값이 왼쪽 피연산자입니다.',
     before:['String[] tokens = {"3", "4", "+", "2", "*"};','Deque<Integer> stack = new ArrayDeque<>();'],
     placeholder:['// TODO','// (숫자면 push, 연산자면 두 번 pop(b, a 순서)해서 계산 후 다시 push)'], rows:8,
     after:['System.out.println(stack.pop());'],
     expected:'14',
     answer:['for (String t : tokens) {','    if (t.equals("+") || t.equals("-") || t.equals("*") || t.equals("/")) {','        int b = stack.pop();','        int a = stack.pop();','        if (t.equals("+")) stack.push(a + b);','        else if (t.equals("-")) stack.push(a - b);','        else if (t.equals("*")) stack.push(a * b);','        else stack.push(a / b);','    } else {','        stack.push(Integer.parseInt(t));','    }','}'],
     note:'뺄셈/나눗셈처럼 순서가 결과에 영향을 주는 연산에서는 b(먼저 꺼낸 값)와 a(나중에 꺼낸 값)를 헷갈리지 않는 게 중요합니다. (3 4 + 2 *) → (3+4)*2 = 14',
     regex:[/int\s+b\s*=\s*stack\.pop\s*\(\s*\)/, /int\s+a\s*=\s*stack\.pop\s*\(\s*\)/, /stack\.push\s*\(/, /Integer\.parseInt\s*\(/]},

    {id:'ST5', level:0, title:'Deque를 Stack처럼 — addFirst/pollFirst',
     concept:'Stack 클래스 대신 Deque를 스택처럼 쓸 때는, push()/pop()/peek() 대신 같은 동작을 하는 addFirst()/pollFirst()/peekFirst()를 직접 써도 됩니다.',
     before:['Deque<Integer> stack = new ArrayDeque<>();'],
     placeholder:['// TODO','// (addFirst로 10, 20, 30 순서로 넣고, pollFirst로 하나 꺼내 top에 저장)'], rows:4,
     after:['System.out.println(top);','System.out.println(stack.peekFirst());'],
     expected:'30, 20',
     answer:['stack.addFirst(10);','stack.addFirst(20);','stack.addFirst(30);','int top = stack.pollFirst();'],
     note:'push() = addFirst(), pop() = pollFirst(), peek() = peekFirst() — 모두 같은 동작의 다른 이름입니다.',
     regex:[/addFirst\s*\(\s*10\s*\)/, /addFirst\s*\(\s*20\s*\)/, /addFirst\s*\(\s*30\s*\)/, /int\s+top\s*=\s*stack\.pollFirst\s*\(\s*\)/]},

    /* ---------------- 2장 Queue ---------------- */
    {id:'QU1', level:1, title:'Queue 기본 — offer & poll',
     concept:'큐는 먼저 넣은 값이 먼저 나옵니다(FIFO). 값을 뒤에 추가하는 연산과, 맨 앞 값을 꺼내면서 동시에 제거하는 연산이 짝을 이룹니다.',
     before:['Queue<Integer> queue = new LinkedList<>();'],
     placeholder:['// TODO','// (1, 2, 3 순서로 offer 한 뒤, 맨 앞 값을 꺼내 first에 저장)'], rows:4,
     after:['System.out.println(first);','System.out.println(queue);'],
     expected:'1, [2, 3]',
     answer:['queue.offer(1);','queue.offer(2);','queue.offer(3);','int first = queue.poll();'], note:'',
     regex:[/offer\s*\(\s*1\s*\)/, /offer\s*\(\s*2\s*\)/, /offer\s*\(\s*3\s*\)/, /int\s+first\s*=\s*queue\.poll\s*\(\s*\)/]},

    {id:'QU2', level:1, title:'peek() — front 값 확인',
     concept:'큐에서 가장 먼저 나갈 값을 제거하지 않고 확인만 하는 연산입니다.',
     before:['Queue<Integer> queue = new LinkedList<>();','queue.offer(5);','queue.offer(6);','queue.offer(7);'],
     placeholder:['int first = /* TODO */;'],
     after:['System.out.println(first);','System.out.println(queue.size());'],
     expected:'5, 3',
     answer:['int first = queue.peek();'], note:'',
     regex:[/int\s+first\s*=\s*queue\.peek\s*\(\s*\)/]},

    {id:'QU3', level:1, title:'BFS 방문 처리 시점',
     concept:'BFS에서 visited 체크는 큐에 넣을 때 하는 게 정석입니다 — poll() 시점에 체크하면 같은 노드가 중복으로 큐에 쌓일 수 있습니다. 인접 노드를 큐에 넣기 직전에 방문 표시를 같이 해야 합니다.',
     before:['int[][] graph = {{1,2},{0,3},{0,3},{1,2}};','boolean[] visited = new boolean[4];','Queue<Integer> queue = new LinkedList<>();','queue.offer(0); visited[0] = true;','List<Integer> order = new ArrayList<>();','while (!queue.isEmpty()) {','    int cur = queue.poll();','    order.add(cur);'],
     placeholder:['    // TODO','    // (graph[cur]의 인접 노드 중 미방문 노드를 찾아 visited 표시 후 큐에 추가)'], rows:3,
     after:['}','System.out.println(order);'],
     expected:'[0, 1, 2, 3]',
     answer:['    for (int next : graph[cur]) {','        if (!visited[next]) {','            visited[next] = true;','            queue.offer(next);','        }','    }'],
     note:'visited 표시는 poll() 직후가 아니라 offer() 직전에 합니다. 그래야 같은 노드가 큐에 두 번 들어가는 걸 막을 수 있습니다.',
     regex:[/for\s*\(\s*int\s+\w+\s*:\s*graph\[\s*cur\s*\]\s*\)/, /visited\[\s*\w+\s*\]\s*=\s*true/, /queue\.offer\s*\(/]},

    {id:'QU4', level:1, title:'레벨별 BFS — 깊이(depth) 세기',
     concept:'큐의 현재 크기(이번 레벨에 있는 노드 수)를 미리 저장해두고, 그 개수만큼만 꺼내 처리하면 한 레벨이 끝나는 시점을 알 수 있습니다. 이 패턴으로 "몇 단계 만에 도달하는지" 깊이를 셀 수 있습니다.',
     before:['int[][] graph = {{1,2},{0,3,4},{0},{1},{1}};','boolean[] visited = new boolean[5];','Queue<Integer> queue = new LinkedList<>();','queue.offer(0); visited[0] = true;','int depth = 0;','while (!queue.isEmpty()) {'],
     placeholder:['    // TODO','    // (현재 큐 크기를 levelSize에 저장, 그 개수만큼 꺼내며 인접 노드를 큐에 추가, 끝나면 depth++)'], rows:6,
     after:['}','System.out.println(depth);'],
     expected:'3',
     answer:['    int levelSize = queue.size();','    for (int i = 0; i < levelSize; i++) {','        int cur = queue.poll();','        for (int next : graph[cur]) {','            if (!visited[next]) {','                visited[next] = true;','                queue.offer(next);','            }','        }','    }','    depth++;'],
     note:'이 패턴은 "미로 최단거리", "단계별 전염 확산"처럼 레벨(깊이) 정보가 필요한 BFS 문제에서 자주 쓰입니다.',
     regex:[/int\s+levelSize\s*=\s*queue\.size\s*\(\s*\)/, /for\s*\(\s*int\s+\w+\s*=\s*0\s*;\s*\w+\s*<\s*levelSize\s*;\s*\w+\+\+\s*\)/, /depth\+\+/]},

    {id:'QU5', level:1, title:'큐 비우며 순서대로 처리',
     concept:'큐가 빌 때까지 반복하면서 꺼낸 값을 차례로 처리하는 가장 기본적인 패턴입니다.',
     before:['Queue<Integer> queue = new LinkedList<>(Arrays.asList(1, 2, 3));','StringBuilder sb = new StringBuilder();'],
     placeholder:['// TODO','// (큐가 빌 때까지 poll()해서 sb에 이어붙이기)'], rows:3,
     after:['System.out.println(sb.toString());'],
     expected:'123',
     answer:['while (!queue.isEmpty()) {','    sb.append(queue.poll());','}'], note:'',
     regex:[/while\s*\(\s*!\s*queue\.isEmpty\s*\(\s*\)\s*\)/, /sb\.append\s*\(\s*queue\.poll\s*\(\s*\)\s*\)/]},

    /* ---------------- 3장 Deque ---------------- */
    {id:'DQ1', level:2, title:'Deque 기본 — addFirst/addLast/pollFirst',
     concept:'Deque는 양쪽 끝에서 모두 추가·제거가 가능합니다. addLast()는 뒤에, addFirst()는 앞에 추가하고, pollFirst()는 맨 앞 값을 꺼내며 제거합니다.',
     before:['Deque<Integer> deque = new ArrayDeque<>();'],
     placeholder:['// TODO','// (addLast로 1, 2를 넣고, addFirst로 0을 넣은 뒤, 맨 앞 값을 꺼내 first에 저장)'], rows:4,
     after:['System.out.println(first);','System.out.println(deque);'],
     expected:'0, [1, 2]',
     answer:['deque.addLast(1);','deque.addLast(2);','deque.addFirst(0);','int first = deque.pollFirst();'], note:'',
     regex:[/addLast\s*\(\s*1\s*\)/, /addLast\s*\(\s*2\s*\)/, /addFirst\s*\(\s*0\s*\)/, /int\s+first\s*=\s*deque\.pollFirst\s*\(\s*\)/]},

    {id:'DQ2', level:2, title:'뒤쪽 조작 — pollLast()',
     concept:'Deque의 뒤쪽도 addLast()로 넣고 pollLast()로 꺼낼 수 있습니다. 앞/뒤 조작이 완전히 대칭입니다.',
     before:['Deque<Integer> deque = new ArrayDeque<>();','deque.addLast(1);','deque.addLast(2);','deque.addLast(3);'],
     placeholder:['int last = /* TODO */;'],
     after:['System.out.println(last);','System.out.println(deque);'],
     expected:'3, [1, 2]',
     answer:['int last = deque.pollLast();'], note:'',
     regex:[/int\s+last\s*=\s*deque\.pollLast\s*\(\s*\)/]},

    {id:'DQ3', level:2, title:'모노토닉 덱 — 슬라이딩 윈도우 최댓값',
     concept:'슬라이딩 윈도우의 최댓값을 구할 때, 덱에 절대 답이 될 수 없는 뒤쪽 인덱스를 미리 버려가며 큰 값만 남깁니다. 새 인덱스를 넣기 전, 덱 맨 뒤 인덱스의 값이 새 값보다 작으면 계속 꺼내 버립니다.',
     before:['int[] nums = {1, 3, -1, -3, 5, 3, 6, 7};','Deque<Integer> deque = new ArrayDeque<>(); // 인덱스를 저장','for (int i = 0; i < nums.length; i++) {'],
     placeholder:['    // TODO','    // (deque 맨 뒤 인덱스의 값이 nums[i]보다 작으면 계속 pollLast, 이후 i를 addLast)'], rows:3,
     after:['}','System.out.println(nums[deque.peekFirst()]);'],
     expected:'7',
     answer:['    while (!deque.isEmpty() && nums[deque.peekLast()] < nums[i]) {','        deque.pollLast();','    }','    deque.addLast(i);'],
     note:'이 구조를 모노토닉 덱(monotonic deque)이라고 합니다. 윈도우 범위를 벗어난 인덱스를 앞에서 추가로 pollFirst() 하면 "슬라이딩 윈도우 최댓값" 문제가 완성됩니다.',
     regex:[/while\s*\(\s*!\s*deque\.isEmpty\s*\(\s*\)\s*&&\s*nums\[\s*deque\.peekLast\s*\(\s*\)\s*\]\s*<\s*nums\[\s*i\s*\]\s*\)/, /deque\.pollLast\s*\(\s*\)/, /deque\.addLast\s*\(\s*i\s*\)/]},

    {id:'DQ4', level:2, title:'회문(palindrome) 검사',
     concept:'양 끝에서 동시에 값을 꺼내 비교하면서 가운데로 좁혀가는 방식으로 회문을 검사할 수 있습니다. 한 번이라도 다르면 결과는 false입니다.',
     before:['String s = "level";','Deque<Character> deque = new ArrayDeque<>();','for (char c : s.toCharArray()) deque.addLast(c);','boolean isPalindrome = true;'],
     placeholder:['// TODO','// (deque.size() > 1인 동안, pollFirst와 pollLast를 비교해서 다르면 isPalindrome = false)'], rows:4,
     after:['System.out.println(isPalindrome);'],
     expected:'true',
     answer:['while (deque.size() > 1) {','    if (deque.pollFirst() != deque.pollLast()) {','        isPalindrome = false;','    }','}'],
     note:'Character처럼 박싱된 타입을 != 로 비교하면 원래는 객체 참조 비교가 됩니다. 다만 char 값(0~127) 범위에서는 자바의 Character 캐시 덕분에 이 예제처럼 의도대로 동작합니다.',
     regex:[/while\s*\(\s*deque\.size\s*\(\s*\)\s*>\s*1\s*\)/, /deque\.pollFirst\s*\(\s*\)\s*!=\s*deque\.pollLast\s*\(\s*\)/, /isPalindrome\s*=\s*false/]},

    {id:'DQ5', level:2, title:'최근 K개만 유지하는 슬라이딩 버퍼',
     concept:'덱은 "최근 K개만 유지"하는 버퍼로도 자주 쓰입니다. 새 값은 뒤에 추가하고, 크기가 K를 넘으면 맨 앞 값을 하나 제거합니다.',
     before:['Deque<Integer> window = new ArrayDeque<>();','int k = 3;','int[] nums = {1, 2, 3, 4, 5};','for (int n : nums) {','    window.addLast(n);'],
     placeholder:['    // TODO','    // (window 크기가 k를 넘으면 pollFirst로 맨 앞을 하나 제거)'], rows:3,
     after:['}','System.out.println(window);'],
     expected:'[3, 4, 5]',
     answer:['    if (window.size() > k) {','        window.pollFirst();','    }'], note:'',
     regex:[/if\s*\(\s*window\.size\s*\(\s*\)\s*>\s*k\s*\)/, /window\.pollFirst\s*\(\s*\)/]},

    /* ---------------- 4장 PriorityQueue ---------------- */
    {id:'PQ1', level:3, title:'PriorityQueue 기본 — 최소 힙',
     concept:'PriorityQueue는 기본적으로 가장 작은 값이 먼저 나오는 최소 힙(min heap)입니다. offer()로 순서 상관없이 넣어도, poll()은 항상 가장 작은 값을 꺼냅니다.',
     before:['Queue<Integer> pq = new PriorityQueue<>();'],
     placeholder:['// TODO','// (5, 1, 3 순서로 offer한 뒤, poll()로 하나 꺼내 min에 저장)'], rows:4,
     after:['System.out.println(min);'],
     expected:'1',
     answer:['pq.offer(5);','pq.offer(1);','pq.offer(3);','int min = pq.poll();'], note:'',
     regex:[/offer\s*\(\s*5\s*\)/, /offer\s*\(\s*1\s*\)/, /offer\s*\(\s*3\s*\)/, /int\s+min\s*=\s*pq\.poll\s*\(\s*\)/]},

    {id:'PQ2', level:3, title:'최대 힙 — Comparator.reverseOrder()',
     concept:'가장 큰 값을 먼저 꺼내고 싶다면, 생성할 때 비교 기준을 거꾸로 뒤집는 Comparator를 넘겨주면 됩니다.',
     before:['Queue<Integer> pq = new PriorityQueue<>(Comparator.reverseOrder());','pq.offer(5); pq.offer(1); pq.offer(3);'],
     placeholder:['int max = /* TODO */;'],
     after:['System.out.println(max);'],
     expected:'5',
     answer:['int max = pq.poll();'],
     note:'new PriorityQueue<>((a, b) -> b - a) 처럼 람다로 직접 비교자를 작성해도 같은 결과입니다.',
     regex:[/int\s+max\s*=\s*pq\.poll\s*\(\s*\)/]},

    {id:'PQ3', level:3, title:'객체 Comparator — 점수 기준 정렬',
     concept:'객체(또는 배열)를 우선순위 큐에 넣을 때는, 어떤 필드를 기준으로 비교할지 Comparator로 직접 정의해야 합니다. score가 낮은 학생부터 나오게 하려면 점수를 오름차순으로 비교합니다.',
     before:['int[][] students = {{1, 85}, {2, 70}, {3, 95}}; // {id, score}','Queue<int[]> pq = new PriorityQueue<>((a, b) -> a[1] - b[1]);'],
     placeholder:['// TODO','// (students의 각 원소를 모두 offer)'], rows:3,
     after:['System.out.println(pq.poll()[0]);'],
     expected:'2',
     answer:['for (int[] s : students) {','    pq.offer(s);','}'],
     note:'(a, b) -> a[1] - b[1]은 "a[1]이 작을수록 앞으로"라는 뜻입니다. 점수가 높은 학생부터 나오게 하려면 b[1] - a[1]로 뒤집으면 됩니다.',
     regex:[/for\s*\(\s*int\s*\[\s*\]\s+\w+\s*:\s*students\s*\)/, /pq\.offer\s*\(/]},

    {id:'PQ4', level:3, title:'K번째로 작은 값',
     concept:'전체를 정렬하지 않아도, 우선순위 큐에서 poll()을 K번 반복하면 K번째로 작은 값을 바로 얻을 수 있습니다.',
     before:['int[] arr = {7, 2, 9, 4, 1, 8};','Queue<Integer> pq = new PriorityQueue<>();','for (int n : arr) pq.offer(n);','int k = 3;'],
     placeholder:['// TODO','// (poll()을 k번 반복해서 마지막으로 꺼낸 값을 kth에 저장)'], rows:4,
     after:['System.out.println(kth);'],
     expected:'4',
     answer:['int kth = 0;','for (int i = 0; i < k; i++) {','    kth = pq.poll();','}'], note:'',
     regex:[/for\s*\(\s*int\s+i\s*=\s*0\s*;\s*i\s*<\s*k\s*;\s*i\+\+\s*\)/, /kth\s*=\s*pq\.poll\s*\(\s*\)/]},

    {id:'PQ5', level:3, title:'다익스트라 비교자 패턴',
     concept:'다익스트라(Dijkstra) 알고리즘에서는 {노드, 현재까지의 거리}를 함께 큐에 넣고, 거리가 짧은 것부터 꺼내야 합니다. int[]의 두 번째 값(거리)을 기준으로 비교자를 만듭니다.',
     before:['Queue<int[]> pq = new PriorityQueue<>((a, b) -> a[1] - b[1]);','pq.offer(new int[]{1, 10});','pq.offer(new int[]{2, 3});','pq.offer(new int[]{3, 7});'],
     placeholder:['int[] nearest = /* TODO */;'],
     after:['System.out.println(nearest[0] + " " + nearest[1]);'],
     expected:'2 3',
     answer:['int[] nearest = pq.poll();'], note:'',
     regex:[/int\s*\[\s*\]\s+nearest\s*=\s*pq\.poll\s*\(\s*\)/]},

    /* ---------------- 5장 변형 연습 ---------------- */
    {id:'V1', level:4, title:'🔁 변형: Stack — push & pop (다른 데이터)',
     concept:'ST1과 같은 패턴입니다. push와 pop 순서만 기억하면 됩니다.',
     before:['Deque<Integer> stack = new ArrayDeque<>();'],
     placeholder:['// TODO','// (7, 8, 9 순서로 push한 뒤, 맨 위 값을 꺼내 top에 저장)'], rows:4,
     after:['System.out.println(top);','System.out.println(stack);'],
     expected:'9, [8, 7]',
     answer:['stack.push(7);','stack.push(8);','stack.push(9);','int top = stack.pop();'], note:'',
     regex:[/push\s*\(\s*7\s*\)/, /push\s*\(\s*8\s*\)/, /push\s*\(\s*9\s*\)/, /int\s+top\s*=\s*stack\.pop\s*\(\s*\)/]},

    {id:'V2', level:4, title:'🔁 변형: Queue — BFS 방문 순서 (다른 그래프)',
     concept:'QU3와 같은 BFS 방문 패턴입니다. 그래프 구조만 다릅니다.',
     before:['int[][] graph = {{1,2,3},{0},{0},{0,4},{3}};','boolean[] visited = new boolean[5];','Queue<Integer> queue = new LinkedList<>();','queue.offer(0); visited[0] = true;','List<Integer> order = new ArrayList<>();','while (!queue.isEmpty()) {','    int cur = queue.poll();','    order.add(cur);'],
     placeholder:['    // TODO','    // (graph[cur]의 인접 노드 중 미방문 노드를 찾아 visited 표시 후 큐에 추가)'], rows:3,
     after:['}','System.out.println(order);'],
     expected:'[0, 1, 2, 3, 4]',
     answer:['    for (int next : graph[cur]) {','        if (!visited[next]) {','            visited[next] = true;','            queue.offer(next);','        }','    }'], note:'',
     regex:[/for\s*\(\s*int\s+\w+\s*:\s*graph\[\s*cur\s*\]\s*\)/, /visited\[\s*\w+\s*\]\s*=\s*true/, /queue\.offer\s*\(/]},

    {id:'V3', level:4, title:'🔁 변형: Deque — 동점 처리 모노토닉 덱',
     concept:'DQ3와 같은 모노토닉 덱 패턴이지만, 이번엔 같은 값이 있을 때도 비교 기준에 포함시켜야 합니다(<=). 그래야 동점인 인덱스 중 더 나중 것이 남습니다.',
     before:['int[] nums = {4, 4, 2, 6, 6, 1};','Deque<Integer> deque = new ArrayDeque<>();','for (int i = 0; i < nums.length; i++) {'],
     placeholder:['    // TODO','    // (deque 맨 뒤 인덱스의 값이 nums[i] 이하이면 계속 pollLast, 이후 i를 addLast)'], rows:3,
     after:['}','System.out.println(nums[deque.peekFirst()]);'],
     expected:'6',
     answer:['    while (!deque.isEmpty() && nums[deque.peekLast()] <= nums[i]) {','        deque.pollLast();','    }','    deque.addLast(i);'],
     note:'< 대신 <=를 쓰면, 값이 같을 때도 이전 인덱스를 버리고 더 나중 인덱스를 남깁니다. 동점 처리 방식에 따라 부등호 방향이 달라질 수 있으니 문제 조건을 꼭 확인하세요.',
     regex:[/while\s*\(\s*!\s*deque\.isEmpty\s*\(\s*\)\s*&&\s*nums\[\s*deque\.peekLast\s*\(\s*\)\s*\]\s*<=\s*nums\[\s*i\s*\]\s*\)/, /deque\.pollLast\s*\(\s*\)/, /deque\.addLast\s*\(\s*i\s*\)/]},

    {id:'V4', level:4, title:'🔁 변형: PriorityQueue — 최대 힙 (다른 데이터)',
     concept:'PQ2와 같은 최대 힙 패턴입니다. 데이터만 다릅니다.',
     before:['Queue<Integer> pq = new PriorityQueue<>(Comparator.reverseOrder());','pq.offer(8); pq.offer(3); pq.offer(6); pq.offer(1); pq.offer(9);'],
     placeholder:['int max = /* TODO */;'],
     after:['System.out.println(max);'],
     expected:'9',
     answer:['int max = pq.poll();'], note:'',
     regex:[/int\s+max\s*=\s*pq\.poll\s*\(\s*\)/]},

    {id:'V5', level:4, title:'🔁 변형: 괄호 검사 — 다른 문자 섞임',
     concept:'ST3와 같은 괄호 검사 패턴이지만, 이번엔 괄호가 아닌 문자도 섞여 있습니다. 괄호가 아닌 문자는 그냥 건너뛰면 됩니다.',
     before:['String s = "a(b(c)d)e";','Deque<Character> stack = new ArrayDeque<>();'],
     placeholder:['// TODO','// (괄호 문자만 push/pop, 괄호가 아니면 무시)'], rows:4,
     after:['System.out.println(stack.isEmpty());'],
     expected:'true',
     answer:['for (char c : s.toCharArray()) {','    if (c == \'(\') stack.push(c);','    else if (c == \')\') stack.pop();','}'], note:'',
     regex:[/for\s*\(\s*char\s+\w+\s*:\s*s\.toCharArray\s*\(\s*\)\s*\)/, /stack\.push\s*\(/, /stack\.pop\s*\(\s*\)/]},

    {id:'V6', level:4, title:'🔁 변형: 후위표기법 — 다른 식',
     concept:'ST4와 같은 후위표기법 계산 패턴입니다. 식만 다릅니다.',
     before:['String[] tokens = {"5","1","2","+","4","*","+","3","-"};','Deque<Integer> stack = new ArrayDeque<>();'],
     placeholder:['// TODO','// (숫자면 push, 연산자면 두 번 pop(b, a 순서)해서 계산 후 다시 push)'], rows:8,
     after:['System.out.println(stack.pop());'],
     expected:'14',
     answer:['for (String t : tokens) {','    if (t.equals("+") || t.equals("-") || t.equals("*") || t.equals("/")) {','        int b = stack.pop();','        int a = stack.pop();','        if (t.equals("+")) stack.push(a + b);','        else if (t.equals("-")) stack.push(a - b);','        else if (t.equals("*")) stack.push(a * b);','        else stack.push(a / b);','    } else {','        stack.push(Integer.parseInt(t));','    }','}'],
     note:'5 1 2 + 4 * + 3 - → 5 + ((1+2)*4) - 3 = 5 + 12 - 3 = 14',
     regex:[/int\s+b\s*=\s*stack\.pop\s*\(\s*\)/, /int\s+a\s*=\s*stack\.pop\s*\(\s*\)/, /stack\.push\s*\(/, /Integer\.parseInt\s*\(/]},

    {id:'V7', level:4, title:'🔁 변형: 회문 검사 — 회문이 아닌 경우',
     concept:'DQ4와 같은 회문 검사 패턴이지만, 이번엔 회문이 아닌 단어입니다.',
     before:['String s = "stack";','Deque<Character> deque = new ArrayDeque<>();','for (char c : s.toCharArray()) deque.addLast(c);','boolean isPalindrome = true;'],
     placeholder:['// TODO','// (deque.size() > 1인 동안, pollFirst와 pollLast를 비교해서 다르면 isPalindrome = false)'], rows:4,
     after:['System.out.println(isPalindrome);'],
     expected:'false',
     answer:['while (deque.size() > 1) {','    if (deque.pollFirst() != deque.pollLast()) {','        isPalindrome = false;','    }','}'], note:'',
     regex:[/while\s*\(\s*deque\.size\s*\(\s*\)\s*>\s*1\s*\)/, /deque\.pollFirst\s*\(\s*\)\s*!=\s*deque\.pollLast\s*\(\s*\)/, /isPalindrome\s*=\s*false/]},

    {id:'V8', level:4, title:'🔁 변형: PriorityQueue — 상위 K개 합',
     concept:'PQ4처럼 poll()을 여러 번 반복하는 패턴인데, 이번엔 꺼낸 값을 누적해서 더합니다 — 가장 큰 값 3개의 합을 구합니다.',
     before:['int[] arr = {4, 1, 9, 3, 7, 2};','Queue<Integer> maxHeap = new PriorityQueue<>(Comparator.reverseOrder());','for (int n : arr) maxHeap.offer(n);','int sum = 0;'],
     placeholder:['// TODO','// (poll()을 3번 반복해서 꺼낸 값을 sum에 누적)'], rows:4,
     after:['System.out.println(sum);'],
     expected:'20',
     answer:['for (int i = 0; i < 3; i++) {','    sum += maxHeap.poll();','}'],
     note:'가장 큰 3개는 9, 7, 4 → 합은 20입니다. poll()을 한 번만 호출하면 안 되고, 반드시 반복문으로 누적해야 합니다.',
     regex:[/for\s*\(\s*int\s+i\s*=\s*0\s*;\s*i\s*<\s*3\s*;\s*i\+\+\s*\)/, /sum\s*\+=\s*maxHeap\.poll\s*\(\s*\)/]}

  ];
