  window.QUESTIONS = [
    {id:'Q0-1', level:0, title:'크기로 배열 선언하기',
     concept:'값을 아직 모를 때도, 칸 수만 먼저 정해서 배열 공간을 미리 잡아둘 수 있는 방법이 있습니다. 이렇게 만들면 각 칸은 자동으로 기본값(default value)으로 채워집니다 — int는 0, boolean은 false, 참조 타입은 null. 크기만 알고 있을 때 배열을 어떻게 선언해야 할지 떠올려보세요.',
     before:[], placeholder:['// TODO: 크기 5인 int 배열 arr 선언'],
     after:['System.out.println(Arrays.toString(arr));'],
     expected:'[0, 0, 0, 0, 0]', answer:['int[] arr = new int[5];'], note:'',
     regex:[/int\s*\[\s*\]\s*arr\s*=\s*new\s*int\s*\[\s*5\s*\]\s*;?/]},

    {id:'Q0-2', level:0, title:'값을 알 때 배열 선언하기 (리터럴)',
     concept:'값을 이미 알고 있다면, 빈 배열을 만들고 하나씩 채우는 대신 선언과 동시에 한 번에 초기화하는 축약형이 있습니다. 단, 이 축약형은 선언 줄에서만 쓸 수 있습니다 — 변수를 먼저 선언해두고 나중에 따로 대입하려고 하면 컴파일 에러가 납니다.',
     before:[], placeholder:['// TODO: 1, 2, 3 값을 가진 int 배열 arr 선언'],
     after:['System.out.println(Arrays.toString(arr));'],
     expected:'[1, 2, 3]', answer:['int[] arr = {1, 2, 3};'], note:'',
     regex:[/int\s*\[\s*\]\s*arr\s*=\s*(?:new\s*int\s*\[\s*\])?\{\s*1\s*,\s*2\s*,\s*3\s*\}\s*;?/]},

    {id:'Q0-3', level:0, title:'2차원 배열 선언하기',
     concept:'2차원 배열은 사실 "배열을 원소로 담은 배열"입니다. 바깥쪽 길이와 안쪽 길이를 각각 따로 지정해서 선언할 수 있는데, 두 길이를 어떤 순서로 표기해야 할지 생각해보세요.',
     before:[], placeholder:['// TODO: 3행 2열짜리 int 2차원 배열 grid 선언'],
     after:['System.out.println(Arrays.deepToString(grid));'],
     expected:'[[0, 0], [0, 0], [0, 0]]', answer:['int[][] grid = new int[3][2];'], note:'',
     regex:[/int\s*\[\s*\]\s*\[\s*\]\s*grid\s*=\s*new\s*int\s*\[\s*3\s*\]\s*\[\s*2\s*\]\s*;?/]},

    {id:'Q0-4', level:0, title:'ArrayList 선언하기 (인터페이스 타입으로)',
     concept:'자바에서 컬렉션(collection)을 다룰 때는, 구체적인 구현 클래스보다 더 넓은 인터페이스 타입으로 변수를 선언해두는 관례가 있습니다. 나중에 구현체만 바꿔도 나머지 코드는 그대로 둘 수 있습니다 — 다형성(polymorphism)의 실용적 이유입니다. 왼쪽엔 어떤 타입을, 오른쪽엔 어떤 타입을 써야 할지 생각해보세요.',
     before:[], placeholder:['// TODO: 빈 정수 ArrayList list 선언'],
     after:['System.out.println(list.size());'],
     expected:'0', answer:['List<Integer> list = new ArrayList<>();'],
     note:'ArrayList<Integer> list = new ArrayList<>();도 동작은 같지만, 다형성을 살리려면 왼쪽을 인터페이스 타입으로 쓰는 게 관례입니다.',
     regex:[/(?:List|ArrayList)\s*<\s*Integer\s*>\s*list\s*=\s*new\s*ArrayList\s*<\s*>\s*\(\s*\)\s*;?/]},

    {id:'Q0-5', level:0, title:'래퍼 클래스(Wrapper Class)로 선언하기',
     concept:'제네릭(generics)을 쓰는 컬렉션은 원시 타입(primitive)을 직접 담을 수 없고, 반드시 객체 타입만 담을 수 있습니다. 그래서 int 대신 그에 대응하는 래퍼 클래스(wrapper class)를 써야 합니다. add(10)처럼 int 값을 넣으면 자바가 자동으로 객체로 변환해주는데, 이를 오토박싱(autoboxing)이라 합니다. (이 개념이 나중에 Q8 함정의 원인이 됩니다.)',
     before:[], placeholder:['// TODO: Integer를 담을 빈 ArrayList numbers 선언'],
     after:['numbers.add(10);','numbers.add(20);','System.out.println(numbers);'],
     expected:'[10, 20]', answer:['List<Integer> numbers = new ArrayList<>();'], note:'',
     regex:[/(?:List|ArrayList)\s*<\s*Integer\s*>\s*numbers\s*=\s*new\s*ArrayList\s*<\s*>\s*\(\s*\)\s*;?/]},

    {id:'Q0-6', level:0, title:'HashMap 선언하기 (타입 파라미터 2개)',
     concept:'Map은 key 타입과 value 타입, 총 두 개의 타입 파라미터를 받습니다. <KeyType, ValueType> 순서를 지켜야 합니다.',
     before:[], placeholder:['// TODO: String을 key로, Integer를 value로 갖는 빈 HashMap scores 선언'],
     after:['System.out.println(scores.size());'],
     expected:'0', answer:['Map<String, Integer> scores = new HashMap<>();'], note:'',
     regex:[/(?:Map|HashMap)\s*<\s*String\s*,\s*Integer\s*>\s*scores\s*=\s*new\s*HashMap\s*<\s*>\s*\(\s*\)\s*;?/]},

    {id:'Q1', level:1, title:'배열 오름차순 정렬',
     concept:'원시 타입(primitive) 배열을 정렬할 때는 비교자(Comparator)를 따로 지정할 수 없고, 항상 오름차순으로만 정렬하는 방법이 있습니다. (Q2의 객체 배열과 비교해보세요)',
     before:['int[] arr = {5, 3, 1, 4, 2};'], placeholder:['// TODO'],
     after:['System.out.println(Arrays.toString(arr));'],
     expected:'[1, 2, 3, 4, 5]', answer:['Arrays.sort(arr);'],
     note:'원시 타입 배열 정렬은 내부적으로 Dual-Pivot Quicksort를 사용하며, 항상 오름차순입니다.',
     regex:[/Arrays\.sort\s*\(\s*arr\s*\)\s*;?/]},

    {id:'Q6', level:1, title:'리스트 인덱스로 값 읽기',
     concept:'리스트에서 특정 위치의 값을 읽어오는 연산은 인덱스(index) 기반 접근이라 O(1)입니다.',
     before:['List<Integer> list = new ArrayList<>(Arrays.asList(10, 20, 30, 40, 50));'], placeholder:['// TODO'],
     after:['System.out.println("val6: " + val6);'],
     expected:'val6: 30', answer:['int val6 = list.get(2);'], note:'',
     regex:[/int\s*val6\s*=\s*list\.get\s*\(\s*2\s*\)\s*;?/]},

    {id:'Q7', level:1, title:'리스트 인덱스 값 수정',
     concept:'리스트의 특정 위치 값을 ‘교체’하는 연산과 ‘새로 끼워넣는’ 연산은 서로 다른 메서드입니다. 교체는 리스트의 길이를 바꾸지 않는다는 점에 주목하세요.',
     before:['// list = [10, 20, 30, 40, 50]'], placeholder:['// TODO'],
     after:['System.out.println(list);'],
     expected:'[10, 99, 30, 40, 50]', answer:['list.set(1, 99);'], note:'',
     regex:[/list\.set\s*\(\s*1\s*,\s*99\s*\)\s*;?/]},

    {id:'Q11', level:1, title:'HashSet 선언과 중복 제거',
     concept:'HashSet은 중복을 허용하지 않고, 입력 순서를 보장하지 않습니다.',
     before:[], placeholder:['Set<Integer> set11 = /* TODO */;'],
     after:['set11.add(1);','set11.add(2);','set11.add(3);','set11.add(2); // 중복 — 무시됨','System.out.println(set11.size());'],
     expected:'3', answer:['Set<Integer> set11 = new HashSet<>();'], note:'',
     regex:[/(?:Set|HashSet)\s*<\s*Integer\s*>\s*set11\s*=\s*new\s*HashSet\s*<\s*>\s*\(\s*\)\s*;?/]},

    {id:'Q16', level:1, title:'Map에 key-value 추가',
     concept:'맵에 키-값 쌍을 넣는 연산은, 키가 이미 있으면 기존 값을 덮어씁니다(overwrite). 즉 ‘추가’와 ‘수정’이 사실 같은 동작으로 처리됩니다.',
     before:['Map<String, Integer> map = new HashMap<>();'], placeholder:['// TODO'],
     after:['System.out.println(map.get("apple"));'],
     expected:'5', answer:['map.put("apple", 5);'], note:'',
     regex:[/map\.put\s*\(\s*"apple"\s*,\s*5\s*\)\s*;?/]},

    {id:'Q20', level:1, title:'Map에서 key 삭제',
     concept:'맵에서 특정 키를 지우는 연산은, 그 키가 원래 없었어도 예외 없이 조용히 넘어갑니다.',
     before:['// map에 "apple"=5가 들어있는 상태'], placeholder:['// TODO'],
     after:['System.out.println(map.size());'],
     expected:'0', answer:['map.remove("apple");'], note:'',
     regex:[/map\.remove\s*\(\s*"apple"\s*\)\s*;?/]},

    {id:'Q9', level:2, title:'값으로 인덱스 찾기',
     concept:'리스트에서 특정 값이 몇 번째 위치에 있는지 찾는 연산이 있습니다. 값이 없으면 -1을 반환합니다.',
     before:['// list = [10, 99, 30, 40, 50]'], placeholder:['// TODO'],
     after:['System.out.println(idx9);'],
     expected:'1', answer:['int idx9 = list.indexOf(99);'], note:'',
     regex:[/int\s*idx9\s*=\s*list\.indexOf\s*\(\s*99\s*\)\s*;?/]},

    {id:'Q12', level:2, title:'Set에 값 존재 여부 확인',
     concept:'Set에 특정 값이 들어있는지 확인하는 연산은 해시(hash) 기반 탐색이라 평균 O(1)입니다. (List에서 같은 종류의 확인은 O(n)이라는 점과 비교해두면 좋습니다.)',
     before:['// set11 = {1, 2, 3}'], placeholder:['boolean has2 = /* TODO */;'],
     after:['System.out.println(has2);'],
     expected:'true', answer:['boolean has2 = set11.contains(2);'], note:'',
     regex:[/boolean\s*has2\s*=\s*set11\.contains\s*\(\s*2\s*\)\s*;?/]},

    {id:'Q19', level:2, title:'Map의 key/value 존재 여부 확인',
     concept:'맵에서 ‘이 키가 있는지’ 확인하는 것과 ‘이 값이 있는지’ 확인하는 것은 비용이 다릅니다. 하나는 해시로 바로 찾아가고, 다른 하나는 모든 값을 하나씩 순회해야 합니다.',
     before:['map.put("apple", 5);'],
     placeholder:['boolean hasKey = /* TODO */;','boolean hasVal = /* TODO */;'],
     after:[], rows:3,
     expected:'hasKey = true, hasVal = true',
     answer:['boolean hasKey = map.containsKey("apple");','boolean hasVal = map.containsValue(5);'], note:'',
     regex:[/containsKey\s*\(\s*"apple"\s*\)/, /containsValue\s*\(\s*5\s*\)/]},

    {id:'Q2', level:2, title:'Integer 배열 내림차순 정렬',
     concept:'비교자(Comparator)를 지정해서 정렬 방향을 바꾸는 기능은 객체 배열(Integer[])에서만 쓸 수 있습니다. 원시 타입 int[]에는 이 옵션이 아예 없습니다 (Q1과 대조). 자바 표준 라이브러리에는 정렬 순서를 거꾸로 뒤집어주는 미리 만들어진 비교자가 있습니다.',
     before:['Integer[] arr2 = {5, 3, 1, 4, 2};'], placeholder:['// TODO'],
     after:['System.out.println(Arrays.toString(arr2));'],
     expected:'[5, 4, 3, 2, 1]', answer:['Arrays.sort(arr2, Collections.reverseOrder());'], note:'',
     regex:[/Arrays\.sort\s*\(\s*arr2\s*,\s*Collections\.reverseOrder\s*\(\s*\)\s*\)\s*;?/]},

    {id:'Q10', level:2, title:'List 내림차순 정렬',
     concept:'배열을 정렬하는 기능과 리스트를 정렬하는 기능은, 사실 서로 다른 클래스에 속해 있습니다. 이름이 비슷해서 헷갈리기 쉬우니 어느 클래스 소속인지 구분해서 기억해두세요.',
     before:['List<Integer> list10 = new ArrayList<>(Arrays.asList(3, 1, 4, 1, 5));'], placeholder:['// TODO'],
     after:['System.out.println(list10);'],
     expected:'[5, 4, 3, 1, 1]', answer:['Collections.sort(list10, Collections.reverseOrder());'], note:'',
     regex:[/Collections\.sort\s*\(\s*list10\s*,\s*Collections\.reverseOrder\s*\(\s*\)\s*\)\s*;?/]},

    {id:'Q3', level:2, title:'배열 특정 범위 채우기',
     concept:'배열의 일부 구간만 골라서 값으로 채우는 기능이 있습니다. 시작 인덱스는 포함되지만, 끝 인덱스는 미포함(exclusive)이라는 점에 주의하세요.',
     before:['int[] arr3 = {0, 0, 0, 0, 0};'], placeholder:['// TODO'],
     after:['System.out.println(Arrays.toString(arr3));'],
     expected:'[0, -1, -1, 0, 0]', answer:['Arrays.fill(arr3, 1, 3, -1);'],
     note:'인덱스 1, 2만 채워지고 인덱스 3은 채워지지 않습니다.',
     regex:[/Arrays\.fill\s*\(\s*arr3\s*,\s*1\s*,\s*3\s*,\s*-1\s*\)\s*;?/]},

    {id:'Q13', level:2, title:'교집합 (Set)',
     concept:'두 집합에서 공통으로 들어있는 원소만 남기고 싶을 때 쓰는 연산이 있습니다. 이 연산은 새 결과를 따로 반환하지 않고, 호출한 집합 자체를 직접 바꿔버립니다(in-place).',
     before:['Set<Integer> setA = new HashSet<>(Arrays.asList(1, 2, 3, 4));','Set<Integer> setB = new HashSet<>(Arrays.asList(3, 4, 5, 6));'],
     placeholder:['// TODO'], after:['System.out.println(setA);'],
     expected:'[3, 4]', answer:['setA.retainAll(setB);'], note:'',
     regex:[/setA\.retainAll\s*\(\s*setB\s*\)\s*;?/]},

    {id:'Q14', level:2, title:'합집합 (Set)',
     concept:'두 집합을 하나로 합치고 싶을 때 쓰는 연산이 있습니다. 중복된 원소는 자동으로 한 번만 남습니다.',
     before:['Set<Integer> setC = new HashSet<>(Arrays.asList(1, 2, 3));','Set<Integer> setD = new HashSet<>(Arrays.asList(3, 4, 5));'],
     placeholder:['// TODO'], after:['System.out.println(setC);'],
     expected:'[1, 2, 3, 4, 5]', answer:['setC.addAll(setD);'], note:'',
     regex:[/setC\.addAll\s*\(\s*setD\s*\)\s*;?/]},

    {id:'Q15', level:2, title:'차집합 (Set)',
     concept:'한 집합에서, 다른 집합과 겹치는 원소들만 골라 제거하고 싶을 때 쓰는 연산이 있습니다.',
     before:['Set<Integer> setE = new HashSet<>(Arrays.asList(1, 2, 3, 4));','Set<Integer> setF = new HashSet<>(Arrays.asList(3, 4, 5));'],
     placeholder:['// TODO'], after:['System.out.println(setE);'],
     expected:'[1, 2]', answer:['setE.removeAll(setF);'], note:'',
     regex:[/setE\.removeAll\s*\(\s*setF\s*\)\s*;?/]},

    {id:'Q17', level:2, title:'key 없을 때 기본값 반환 (저장은 안 됨)',
     concept:'맵에 없는 키를 조회할 때, 예외 대신 미리 정해둔 기본값을 돌려받고 싶을 때 쓰는 연산이 있습니다. 중요한 건, 이 연산이 맵에 그 키를 실제로 저장하지는 않는다는 점입니다 — 이 부분이 가장 헷갈리기 쉽습니다.',
     before:[], placeholder:['int val17 = /* TODO */;'],
     after:['System.out.println(val17);','System.out.println(map.containsKey("banana"));'],
     expected:'0, false', answer:['int val17 = map.getOrDefault("banana", 0);'], note:'',
     regex:[/int\s*val17\s*=\s*map\.getOrDefault\s*\(\s*"banana"\s*,\s*0\s*\)\s*;?/]},

    {id:'Q5', level:3, title:'배열 → ArrayList 변환',
     concept:'배열을 리스트로 감싸주는 기능이 있는데, 이걸로 바로 만든 리스트는 사실 배열을 그대로 감싼 고정 크기(fixed-size) 리스트라서 add/remove가 불가능합니다(UnsupportedOperationException). 진짜 자유롭게 추가·삭제 가능한 리스트가 필요하다면 한 단계를 더 거쳐야 합니다.',
     before:['Integer[] arr5 = {10, 20, 30};'], placeholder:['// TODO'],
     after:['System.out.println(list5);'],
     expected:'[10, 20, 30]', answer:['List<Integer> list5 = new ArrayList<>(Arrays.asList(arr5));'],
     note:'new ArrayList<>()로 한 번 더 감싸지 않으면 이후 add()/remove() 호출 시 런타임 예외가 발생합니다.',
     regex:[/List\s*<\s*Integer\s*>\s*list5\s*=\s*new\s*ArrayList\s*<\s*>\s*\(\s*Arrays\.asList\s*\(\s*arr5\s*\)\s*\)\s*;?/]},

    {id:'Q8', level:3, title:'인덱스 삭제 vs 값 삭제',
     concept:'리스트의 삭제 연산은 오버로딩(overloading)된 메서드라서, 인덱스로 지우는 버전과 값으로 지우는 버전이 따로 존재합니다. 정수를 그대로 넣으면 컴파일러는 그걸 인덱스로 받아들입니다. 그렇다면 "값으로 지우고 싶다"는 의도를 컴파일러에게 어떻게 전달해야 할까요? (Q0-5의 오토박싱 개념을 다시 떠올려보세요)',
     before:['// list = [10, 99, 30, 40, 50]'], placeholder:['// TODO  (값 30을 삭제하고 싶음)'],
     after:['System.out.println(list);'],
     expected:'[10, 99, 40, 50]', answer:['list.remove(Integer.valueOf(30));'],
     note:'list.remove(30)이라고 쓰면 인덱스 30번째 원소를 지우려다 IndexOutOfBoundsException이 납니다.',
     regex:[/list\.remove\s*\(\s*Integer\.valueOf\s*\(\s*30\s*\)\s*\)\s*;?/]},

    {id:'Q18', level:3, title:'빈도수 카운팅 패턴',
     concept:'각 단어가 몇 번 등장했는지 세고 싶을 때 자주 쓰는 전형적인 패턴이 있습니다. 처음 보는 단어는 0부터 시작해서 1을 더하고, 이미 본 단어는 기존 횟수에 1을 더하면 됩니다 — 이 두 경우를 한 줄로 동시에 처리하려면 어떻게 해야 할까요? 코딩테스트에서 거의 항상 등장하는 패턴이니 꼭 손에 익혀두세요.',
     before:['String[] words = {"a", "b", "a", "c", "a", "b"};','Map<String, Integer> freq = new HashMap<>();','for (String w : words) {'],
     placeholder:['    // TODO'],
     after:['}','System.out.println(freq.get("a"));','System.out.println(freq.get("b"));'],
     expected:'3, 2', answer:['freq.put(w, freq.getOrDefault(w, 0) + 1);'],
     note:'첫 등장 시 getOrDefault가 0을 반환해 1로 시작하고, 이후 등장할 때마다 기존 값에 1씩 더해집니다.',
     regex:[/freq\.put\s*\(\s*w\s*,\s*freq\.getOrDefault\s*\(\s*w\s*,\s*0\s*\)\s*\+\s*1\s*\)\s*;?/]},

    {id:'Q4', level:3, title:'2차원 배열 정렬 (람다 비교자)',
     concept:'2차원 배열은 사실 1차원 배열들을 원소로 담은 객체 배열입니다. 그래서 1차원 int[](Q1)와 달리, 정렬 기준을 직접 정해줄 수 있는 방법이 있습니다. 각 행의 0번째 값을 기준으로 두 행을 비교하려면 어떤 식을 써야 할지 생각해보세요.',
     before:['int[][] arr4 = {{3, 1}, {1, 5}, {2, 3}};'], placeholder:['// TODO  (0번 인덱스 기준 오름차순)'],
     after:['System.out.println(Arrays.deepToString(arr4));'],
     expected:'[[1, 5], [2, 3], [3, 1]]', answer:['Arrays.sort(arr4, (a, b) -> a[0] - b[0]);'],
     note:'a[0] - b[0]이 음수면 a가 앞, 양수면 b가 앞으로 정렬됩니다.',
     regex:[/Arrays\.sort\s*\(\s*arr4\s*,\s*\(\s*a\s*,\s*b\s*\)\s*->\s*(?:a\[0\]\s*-\s*b\[0\]|Integer\.compare\s*\(\s*a\[0\]\s*,\s*b\[0\]\s*\))\s*\)\s*;?/]},

    {id:'Q13b', level:4, title:'🔁 변형: 교집합 (다른 데이터)',
     concept:'두 집합에서 공통으로 들어있는 원소만 남기고 싶을 때 쓰는 연산이 있습니다. 이 연산은 새 결과를 따로 반환하지 않고, 호출한 집합 자체를 직접 바꿔버립니다(in-place). (Q13과 같은 패턴, 다른 데이터)',
     before:['Set<Integer> setA = new HashSet<>(Arrays.asList(10, 20, 30, 40));','Set<Integer> setB = new HashSet<>(Arrays.asList(20, 40, 50));'],
     placeholder:['// TODO'], after:['System.out.println(setA);'],
     expected:'[20, 40]', answer:['setA.retainAll(setB);'], note:'',
     regex:[/setA\.retainAll\s*\(\s*setB\s*\)\s*;?/]},

    {id:'Q14b', level:4, title:'🔁 변형: 합집합 (다른 데이터)',
     concept:'두 집합을 하나로 합치고 싶을 때 쓰는 연산이 있습니다. 중복된 원소는 자동으로 한 번만 남습니다. (Q14와 같은 패턴, 다른 데이터)',
     before:['Set<Integer> setC = new HashSet<>(Arrays.asList(1, 3, 5));','Set<Integer> setD = new HashSet<>(Arrays.asList(2, 3, 4));'],
     placeholder:['// TODO'], after:['System.out.println(setC);'],
     expected:'[1, 2, 3, 4, 5]', answer:['setC.addAll(setD);'], note:'',
     regex:[/setC\.addAll\s*\(\s*setD\s*\)\s*;?/]},

    {id:'Q15b', level:4, title:'🔁 변형: 차집합 (다른 데이터)',
     concept:'한 집합에서, 다른 집합과 겹치는 원소들만 골라 제거하고 싶을 때 쓰는 연산이 있습니다. (Q15와 같은 패턴, 다른 데이터)',
     before:['Set<Integer> setE = new HashSet<>(Arrays.asList(1, 2, 3, 4, 5));','Set<Integer> setF = new HashSet<>(Arrays.asList(2, 4));'],
     placeholder:['// TODO'], after:['System.out.println(setE);'],
     expected:'[1, 3, 5]', answer:['setE.removeAll(setF);'], note:'',
     regex:[/setE\.removeAll\s*\(\s*setF\s*\)\s*;?/]},

    {id:'Q17b', level:4, title:'🔁 변형: 기본값 반환 (다른 데이터)',
     concept:'맵에 없는 키를 조회할 때, 예외 대신 미리 정해둔 기본값을 돌려받고 싶을 때 쓰는 연산이 있습니다. 이 연산은 맵에 그 키를 실제로 저장하지는 않습니다. (Q17과 같은 패턴, 다른 데이터)',
     before:['Map<String, Integer> map = new HashMap<>();','map.put("apple", 5);'],
     placeholder:['int val = /* TODO */;'], after:['System.out.println(val);'],
     expected:'-1', answer:['int val = map.getOrDefault("kiwi", -1);'], note:'',
     regex:[/int\s*val\s*=\s*map\.getOrDefault\s*\(\s*"kiwi"\s*,\s*-1\s*\)\s*;?/]},

    {id:'Q8b', level:4, title:'🔁 변형: 인덱스 삭제 vs 값 삭제 (다른 데이터)',
     concept:'리스트의 삭제 연산은 오버로딩(overloading)된 메서드라서, 인덱스로 지우는 버전과 값으로 지우는 버전이 따로 존재합니다. 정수를 그대로 넣으면 인덱스로 해석된다는 점을 떠올려보세요. (Q8과 같은 패턴, 다른 데이터)',
     before:['List<Integer> list = new ArrayList<>(Arrays.asList(5, 15, 25, 35));'],
     placeholder:['// TODO (값 25를 삭제하고 싶음)'], after:['System.out.println(list);'],
     expected:'[5, 15, 35]', answer:['list.remove(Integer.valueOf(25));'], note:'',
     regex:[/list\.remove\s*\(\s*Integer\.valueOf\s*\(\s*25\s*\)\s*\)\s*;?/]},

    {id:'Q18b', level:4, title:'🔁 변형: 빈도수 카운팅 (다른 데이터)',
     concept:'각 항목이 몇 번 등장했는지 셀 때 쓰는 전형적인 패턴이 있습니다. 처음 보는 항목은 0부터 시작해서 1을 더하고, 이미 본 항목은 기존 횟수에 1을 더합니다. (Q18과 같은 패턴, 다른 데이터)',
     before:['String[] fruits = {"apple", "banana", "apple", "apple", "banana", "cherry"};','Map<String, Integer> freq = new HashMap<>();','for (String f : fruits) {'],
     placeholder:['    // TODO'],
     after:['}','System.out.println(freq.get("apple"));','System.out.println(freq.get("banana"));'],
     expected:'3, 2', answer:['freq.put(f, freq.getOrDefault(f, 0) + 1);'], note:'',
     regex:[/freq\.put\s*\(\s*f\s*,\s*freq\.getOrDefault\s*\(\s*f\s*,\s*0\s*\)\s*\+\s*1\s*\)\s*;?/]},

    {id:'Q2b', level:4, title:'🔁 변형: 객체 배열 내림차순 (다른 데이터)',
     concept:'비교자(Comparator)를 지정해서 정렬 방향을 바꾸는 기능은 객체 배열에서만 쓸 수 있습니다. 자바 표준 라이브러리에는 정렬 순서를 거꾸로 뒤집어주는 미리 만들어진 비교자가 있습니다. (Q2와 같은 패턴, 다른 데이터)',
     before:['Integer[] nums = {7, 2, 9, 4, 1};'], placeholder:['// TODO (내림차순)'],
     after:['System.out.println(Arrays.toString(nums));'],
     expected:'[9, 7, 4, 2, 1]', answer:['Arrays.sort(nums, Collections.reverseOrder());'], note:'',
     regex:[/Arrays\.sort\s*\(\s*nums\s*,\s*Collections\.reverseOrder\s*\(\s*\)\s*\)\s*;?/]},

    {id:'Q10b', level:4, title:'🔁 변형: 리스트 내림차순 (다른 데이터)',
     concept:'배열을 정렬하는 기능과 리스트를 정렬하는 기능은 서로 다른 클래스에 속해 있습니다. 이름이 비슷해서 헷갈리기 쉬우니 어느 클래스 소속인지 떠올려보세요. (Q10과 같은 패턴, 다른 데이터)',
     before:['List<Integer> list2 = new ArrayList<>(Arrays.asList(8, 2, 6, 4));'], placeholder:['// TODO (내림차순)'],
     after:['System.out.println(list2);'],
     expected:'[8, 6, 4, 2]', answer:['Collections.sort(list2, Collections.reverseOrder());'], note:'',
     regex:[/Collections\.sort\s*\(\s*list2\s*,\s*Collections\.reverseOrder\s*\(\s*\)\s*\)\s*;?/]},

    {id:'Q9b', level:4, title:'🔁 변형: 값으로 인덱스 찾기 (다른 데이터)',
     concept:'리스트에서 특정 값이 몇 번째 위치에 있는지 찾는 연산이 있습니다. 값이 없으면 -1을 반환합니다. (Q9와 같은 패턴, 다른 데이터)',
     before:['List<Integer> list3 = new ArrayList<>(Arrays.asList(7, 14, 21, 28));'], placeholder:['// TODO'],
     after:['System.out.println(idx);'],
     expected:'2', answer:['int idx = list3.indexOf(21);'], note:'',
     regex:[/int\s*idx\s*=\s*list3\.indexOf\s*\(\s*21\s*\)\s*;?/]},

    {id:'Q5b', level:4, title:'🔁 변형: 배열 → ArrayList 변환 (다른 데이터)',
     concept:'배열을 리스트로 감싸주는 기능이 있는데, 그걸로 바로 만든 리스트는 고정 크기(fixed-size)라서 add/remove가 불가능합니다. 진짜 자유롭게 추가·삭제 가능한 리스트가 필요하다면 한 단계를 더 거쳐야 합니다. (Q5와 같은 패턴, 다른 데이터)',
     before:['Integer[] src = {100, 200, 300};'], placeholder:['// TODO'],
     after:['System.out.println(result);'],
     expected:'[100, 200, 300]', answer:['List<Integer> result = new ArrayList<>(Arrays.asList(src));'], note:'',
     regex:[/List\s*<\s*Integer\s*>\s*result\s*=\s*new\s*ArrayList\s*<\s*>\s*\(\s*Arrays\.asList\s*\(\s*src\s*\)\s*\)\s*;?/]},
    {id:'CT1', level:1, title:'코테: 배열 길이 구하기',
     concept:'배열의 길이는 length 필드로 확인합니다.',
     before:['int[] arr = {1,2,3,4,5};'], placeholder:['// TODO'],
     after:['System.out.println(len);'],
     expected:'5', answer:['int len = arr.length;'], note:'',
     regex:[/int\s*len\s*=\s*arr\.length\s*;?/]},

    {id:'CT2', level:1, title:'코테: List 크기 구하기',
     concept:'List의 원소 개수는 size() 메서드로 확인합니다.',
     before:['List<Integer> list = Arrays.asList(1,2,3);'], placeholder:['// TODO'],
     after:['System.out.println(size);'],
     expected:'3', answer:['int size = list.size();'], note:'',
     regex:[/int\s*size\s*=\s*list\.size\s*\(\s*\)\s*;?/]},

    {id:'CT3', level:1, title:'코테: 배열 출력하기',
     concept:'배열 내용을 확인할 때는 Arrays.toString()을 사용합니다.',
     before:['int[] arr = {1,2,3};'], placeholder:['// TODO'],
     after:[],
     expected:'[1, 2, 3]', answer:['System.out.println(Arrays.toString(arr));'], note:'',
     regex:[/Arrays\.toString\s*\(\s*arr\s*\)/]},

    {id:'CT4', level:2, title:'코테: 배열 합계 구하기',
     concept:'배열 합계는 Stream API로 빠르게 계산할 수 있습니다.',
     before:['int[] arr = {1,2,3,4,5};'], placeholder:['// TODO'],
     after:['System.out.println(sum);'],
     expected:'15', answer:['int sum = Arrays.stream(arr).sum();'], note:'',
     regex:[/Arrays\.stream\s*\(\s*arr\s*\)\.sum\s*\(\s*\)/]},

    {id:'CT5', level:2, title:'코테: 배열 최대값',
     concept:'배열의 최대값을 찾습니다.',
     before:['int[] arr = {5,3,9,1};'], placeholder:['// TODO'],
     after:['System.out.println(max);'],
     expected:'9', answer:['int max = Arrays.stream(arr).max().getAsInt();'], note:'',
     regex:[/int\s*max\s*=\s*Arrays\.stream\s*\(\s*arr\s*\)\.max\s*\(\s*\)\.getAsInt\s*\(\s*\)\s*;?/]},

    {id:'CT6', level:2, title:'코테: 배열 최소값',
     concept:'배열의 최소값을 찾습니다.',
     before:['int[] arr = {5,3,9,1};'], placeholder:['// TODO'],
     after:['System.out.println(min);'],
     expected:'1', answer:['int min = Arrays.stream(arr).min().getAsInt();'], note:'',
     regex:[/int\s*min\s*=\s*Arrays\.stream\s*\(\s*arr\s*\)\.min\s*\(\s*\)\.getAsInt\s*\(\s*\)\s*;?/]},

    {id:'CT7', level:2, title:'코테: 리스트 → 배열 변환',
     concept:'List를 배열로 변환합니다.',
     before:['List<Integer> list = Arrays.asList(1,2,3);'], placeholder:['// TODO'],
     after:['System.out.println(Arrays.toString(arr));'],
     expected:'[1, 2, 3]', answer:['Integer[] arr = list.toArray(new Integer[0]);'], note:'',
     regex:[/Integer\s*\[\s*\]\s*arr\s*=\s*list\.toArray\s*\(\s*new\s*Integer\s*\[\s*0\s*\]\s*\)\s*;?/]},

    {id:'CT8', level:2, title:'코테: List → Set 중복 제거',
     concept:'Set 생성자를 이용해 중복을 제거합니다.',
     before:['List<Integer> list = Arrays.asList(1,2,2,3,3);'], placeholder:['// TODO'],
     after:['System.out.println(set.size());'],
     expected:'3', answer:['Set<Integer> set = new HashSet<>(list);'], note:'',
     regex:[/(?:Set|HashSet)\s*<\s*Integer\s*>\s*set\s*=\s*new\s*HashSet\s*<\s*>\s*\(\s*list\s*\)\s*;?/]},

    {id:'CT9', level:2, title:'코테: Set → List 변환',
     concept:'Set을 List로 변환합니다.',
     before:['Set<Integer> set = new HashSet<>(Arrays.asList(1,2,3));'], placeholder:['// TODO'],
     after:['System.out.println(list.size());'],
     expected:'3', answer:['List<Integer> list = new ArrayList<>(set);'], note:'',
     regex:[/(?:List|ArrayList)\s*<\s*Integer\s*>\s*list\s*=\s*new\s*ArrayList\s*<\s*>\s*\(\s*set\s*\)\s*;?/]},

    {id:'CT10', level:3, title:'코테: 배열 복사',
     concept:'참조 공유가 아닌 실제 복사를 수행합니다.',
     before:['int[] arr = {1,2,3};'], placeholder:['// TODO'],
     after:['System.out.println(copy.length);'],
     expected:'3', answer:['int[] copy = Arrays.copyOf(arr, arr.length);'], note:'',
     regex:[/Arrays\.copyOf\s*\(\s*arr\s*,\s*arr\.length\s*\)/]},

    {id:'CT11', level:3, title:'코테: Map에 없으면 추가',
     concept:'키가 이미 있으면 값을 바꾸지 않고, 키가 없을 때만 값을 넣습니다.',
     before:['Map<String,Integer> map = new HashMap<>();','map.put("apple", 5);'], placeholder:['// TODO'],
     after:['System.out.println(map.get("apple"));'],
     expected:'5', answer:['map.putIfAbsent("apple", 0);'],
     note:'"apple" 키가 이미 있으므로 0으로 덮어써지지 않고 기존 값 5가 그대로 유지됩니다. map.put("apple", 0)이었다면 5가 0으로 바뀌었을 것입니다.',
     regex:[/map\.putIfAbsent\s*\(\s*"apple"\s*,\s*0\s*\)\s*;?/]},

    {id:'CT12', level:3, title:'코테: Map entrySet 순회',
     concept:'Map을 순회할 때 가장 많이 사용하는 패턴입니다. entrySet()으로 key와 value를 동시에 꺼내올 수 있습니다.',
     before:['Map<String,Integer> map = new HashMap<>();','map.put("apple", 3);','map.put("banana", 5);','int total = 0;'],
     placeholder:['// TODO: entrySet으로 순회하며 total에 value를 더하기'],
     after:['System.out.println(total);'], rows:3,
     expected:'8',
     answer:['for (Map.Entry<String,Integer> e : map.entrySet()) { total += e.getValue(); }'], note:'',
     regex:[/for\s*\(\s*Map\.Entry\s*<\s*String\s*,\s*Integer\s*>\s*\w+\s*:\s*map\.entrySet\s*\(\s*\)\s*\)/, /total\s*\+=\s*\w+\.getValue\s*\(\s*\)/]},

    {id:'IO1', level:5, title:'입출력: Scanner로 정수 입력받기',
     concept:'Scanner는 표준 입력(standard input)을 토큰(공백·줄바꿈 기준) 단위로 끊어 읽습니다. 그중에서 정수 하나만 읽어오는 메서드가 있습니다.',
     before:['// 입력: "5" 한 줄이 들어온다고 가정','Scanner sc = new Scanner(System.in);'],
     placeholder:['// TODO: 정수 하나를 입력받아 n에 저장'],
     after:['System.out.println(n);'],
     expected:'5', answer:['int n = sc.nextInt();'], note:'',
     regex:[/int\s*n\s*=\s*sc\.nextInt\s*\(\s*\)\s*;?/]},

    {id:'IO2', level:5, title:'입출력: Scanner로 문자열 한 줄 입력받기',
     concept:'nextInt()나 next()는 공백을 기준으로 한 토큰만 읽습니다. 공백이 포함된 한 줄 전체를 통째로 읽고 싶을 때 쓰는 메서드가 따로 있습니다.',
     before:['// 입력: "hello world" 한 줄이 들어온다고 가정','Scanner sc = new Scanner(System.in);'],
     placeholder:['// TODO: 한 줄 전체를 line에 저장'],
     after:['System.out.println(line);'],
     expected:'hello world', answer:['String line = sc.nextLine();'], note:'',
     regex:[/String\s*line\s*=\s*sc\.nextLine\s*\(\s*\)\s*;?/]},

    {id:'IO3', level:5, title:'입출력: ⚠️ 함정 — nextInt() 뒤의 nextLine()',
     concept:'nextInt()는 숫자만 읽고, 그 줄 끝의 줄바꿈 문자는 입력 버퍼에 그대로 남겨둡니다. 바로 다음에 nextLine()을 호출하면 새 줄이 아니라 버퍼에 남아있던 그 줄바꿈 문자만 읽혀서 빈 문자열이 반환됩니다. 코딩테스트에서 정수와 문자열 입력을 섞어 받을 때 가장 많이 걸리는 함정이니, 어떻게 해결해야 할지 생각해보세요.',
     before:['// 입력: "3" 그리고 다음 줄에 "hello" 가 들어온다고 가정','Scanner sc = new Scanner(System.in);','int num = sc.nextInt();'],
     placeholder:['// TODO: 버퍼에 남은 줄바꿈을 먼저 버리고, 다음 줄을 line에 저장'], rows:3,
     after:['System.out.println(line);'],
     expected:'hello', answer:['sc.nextLine();','String line = sc.nextLine();'],
     note:'첫 번째 nextLine()이 nextInt() 뒤에 남은 줄바꿈 문자를 소비(consume)하는 역할을 합니다. 이 줄이 빠지면 line에 빈 문자열("")이 들어가는 게 바로 이 문제의 함정입니다.',
     regex:[/sc\.nextLine\s*\(\s*\)\s*;[\s\S]*String\s*line\s*=\s*sc\.nextLine\s*\(\s*\)\s*;?/]},

    {id:'IO4', level:5, title:'입출력: BufferedReader로 한 줄 읽기',
     concept:'Scanner는 입력을 파싱(parsing)하는 과정 때문에 비교적 느립니다. 입력 줄 수가 많은 코딩테스트에서는, 버퍼링된 스트림으로 한 줄을 통째로 빠르게 읽어오는 방법을 더 선호합니다. System.in을 감싸는 두 단계를 거쳐야 합니다.',
     before:['// 입력: "hello" 한 줄이 들어온다고 가정','BufferedReader br = new BufferedReader(new InputStreamReader(System.in));'],
     placeholder:['// TODO: 한 줄을 읽어 line에 저장'],
     after:['System.out.println(line);'],
     expected:'hello', answer:['String line = br.readLine();'],
     note:'readLine()은 IOException을 던질 수 있어서, 보통 메서드 선언에 throws IOException을 추가해 처리합니다. (이 채점기는 throws 여부까지는 검사하지 않습니다.)',
     regex:[/String\s*line\s*=\s*br\.readLine\s*\(\s*\)\s*;?/]},

    {id:'IO5', level:5, title:'입출력: StringTokenizer로 토큰 분리',
     concept:'한 줄에 공백으로 구분된 값이 여러 개 들어올 때, 이를 토큰(token) 단위로 하나씩 잘라주는 클래스가 있습니다. 생성자에 원본 문자열을 넘기면, 호출할 때마다 다음 토큰을 하나씩 돌려줍니다.',
     before:['// 입력: "3 5 7" 한 줄이 들어온다고 가정','String line = "3 5 7";'],
     placeholder:['// TODO: line을 공백 기준으로 분리하는 StringTokenizer st 생성'],
     after:['System.out.println(st.nextToken());','System.out.println(st.nextToken());','System.out.println(st.nextToken());'],
     expected:'3, 5, 7', answer:['StringTokenizer st = new StringTokenizer(line);'], note:'',
     regex:[/StringTokenizer\s*st\s*=\s*new\s*StringTokenizer\s*\(\s*line\s*\)\s*;?/]},

    {id:'IO6', level:5, title:'입출력: BufferedReader + StringTokenizer 조합',
     concept:'BufferedReader로 빠르게 한 줄을 읽고, 그 줄을 StringTokenizer로 토큰 단위로 쪼개는 조합은 코딩테스트에서 가장 흔한 입력 처리 패턴입니다. 단, StringTokenizer가 돌려주는 토큰은 항상 String이라는 점에 주의하세요 — 숫자로 쓰려면 한 단계를 더 거쳐야 합니다.',
     before:['// 입력: "10 20" 한 줄이 들어온다고 가정','BufferedReader br = new BufferedReader(new InputStreamReader(System.in));','StringTokenizer st = new StringTokenizer(br.readLine());'],
     placeholder:['int a = /* TODO */;','int b = /* TODO */;'], rows:3,
     after:['System.out.println(a + b);'],
     expected:'30',
     answer:['int a = Integer.parseInt(st.nextToken());','int b = Integer.parseInt(st.nextToken());'],
     note:'StringTokenizer가 돌려주는 토큰은 항상 String이므로, 숫자로 쓰려면 Integer.parseInt()로 직접 변환해야 합니다.',
     regex:[/int\s*a\s*=\s*Integer\.parseInt\s*\(\s*st\.nextToken\s*\(\s*\)\s*\)\s*;?/, /int\s*b\s*=\s*Integer\.parseInt\s*\(\s*st\.nextToken\s*\(\s*\)\s*\)\s*;?/]},

    {id:'IO7', level:5, title:'입출력: StringBuilder로 문자열 누적',
     concept:'반복문 안에서 String을 +=로 계속 이어붙이면, 그때마다 새로운 String 객체가 만들어져서 데이터가 많아질수록 점점 느려집니다. 내부 버퍼를 직접 수정(mutate)해서 훨씬 빠르게 문자열을 이어붙이는 클래스가 있습니다.',
     before:['StringBuilder sb = new StringBuilder();','for (int i = 1; i <= 3; i++) {'],
     placeholder:['    // TODO: sb에 i를 추가'],
     after:['}','System.out.println(sb.toString());'],
     expected:'123', answer:['sb.append(i);'],
     note:'String을 +=로 반복 이어붙이면 매번 새 String 객체가 생성되어 느려집니다(대략 O(n²)). StringBuilder.append()는 내부 버퍼를 직접 수정해서 훨씬 빠릅니다.',
     regex:[/sb\.append\s*\(\s*i\s*\)\s*;?/]},

    {id:'IO8', level:5, title:'입출력: StringBuilder로 줄바꿈 포함 출력',
     concept:'여러 줄을 출력할 때 매번 System.out.println()을 호출하는 대신, StringBuilder에 줄바꿈 문자(\\n)를 함께 누적한 뒤 마지막에 한 번만 출력하는 방법이 있습니다. 출력 호출 횟수를 줄이면 I/O 비용을 절약할 수 있어 입력이 많은 코딩테스트에서 유리합니다.',
     before:['StringBuilder sb = new StringBuilder();','String[] words = {"apple", "banana", "cherry"};','for (String w : words) {'],
     placeholder:['    // TODO: sb에 w와 줄바꿈(\\n)을 함께 추가'],
     after:['}','System.out.print(sb);'],
     expected:'apple\nbanana\ncherry\n', answer:['sb.append(w).append("\\n");'],
     note:'append()는 자기 자신을 반환하므로 .append(w).append("\\n")처럼 메서드 체이닝이 가능합니다.',
     regex:[/sb\.append\s*\(\s*w\s*\).*\.append\s*\(\s*"\\n"\s*\)\s*;?/]}

  ];
