window.CHAPTER_DATA = window.CHAPTER_DATA || {};
window.CHAPTER_DATA[2] = window.CHAPTER_DATA[2] || {};
window.CHAPTER_DATA[2].questions = [
    {id:'CL1', level:0, title:'생성자(Constructor) 정의',
     concept:'생성자는 객체가 생성될 때 자동으로 호출되는, 클래스와 이름이 같은 특수한 메서드입니다. 반환 타입을 적지 않습니다.',
     before:['class Person {','    String name;','    int age;'],
     placeholder:['    // TODO: name과 age를 매개변수로 받아 필드를 초기화하는 생성자 작성'], rows:4,
     after:['}','Person p = new Person("철수", 20);','System.out.println(p.name + " " + p.age);'],
     expected:'철수 20',
     answer:['    Person(String name, int age) {','        this.name = name;','        this.age = age;','    }'],
     note:'this.name은 필드, name은 매개변수입니다. 이름이 같을 때 this를 안 붙이면 매개변수가 자기 자신에게 대입되어 필드는 그대로 null로 남습니다.',
     regex:[/Person\s*\(\s*String\s+name\s*,\s*int\s+age\s*\)/, /this\.name\s*=\s*name/, /this\.age\s*=\s*age/]},
    {id:'CL2', level:0, title:'값을 반환하는 메서드',
     concept:'메서드는 클래스 안에 정의된 함수입니다. 반환 타입, 메서드 이름, 매개변수, return문으로 구성됩니다.',
     before:['class Rectangle {','    int width, height;','    Rectangle(int width, int height) { this.width = width; this.height = height; }'],
     placeholder:['    // TODO: 넓이(width*height)를 반환하는 area() 메서드 작성'], rows:3,
     after:['}','Rectangle r = new Rectangle(3, 4);','System.out.println(r.area());'],
     expected:'12',
     answer:['    int area() {','        return width * height;','    }'], note:'',
     regex:[/int\s+area\s*\(\s*\)\s*\{/, /return\s+width\s*\*\s*height/]},
    {id:'CL3', level:0, title:'생성자 오버로딩',
     concept:'생성자를 하나라도 직접 정의하면, 자바가 자동으로 제공하던 매개변수 없는 기본 생성자는 더 이상 제공되지 않습니다. 매개변수 없는 생성자도 필요하다면 직접 추가해야 합니다.',
     before:['class Box {','    int size;','    Box(int size) { this.size = size; }'],
     placeholder:['    // TODO: 매개변수 없이 size를 0으로 초기화하는 생성자(오버로딩) 추가'], rows:3,
     after:['}','Box b = new Box();','System.out.println(b.size);'],
     expected:'0',
     answer:['    Box() {','        this.size = 0;','    }'],
     note:'한 클래스에 매개변수 개수나 타입이 다른 생성자를 여러 개 두는 것을 생성자 오버로딩이라고 합니다.',
     regex:[/Box\s*\(\s*\)\s*\{/, /this\.size\s*=\s*0/]},
    {id:'CL4', level:0, title:'this()로 생성자끼리 호출',
     concept:'한 생성자 안에서 같은 클래스의 다른 생성자를 호출할 수 있습니다. this(...)를 쓰면 되는데, 반드시 생성자의 첫 줄에서만 호출할 수 있습니다.',
     before:['class Point {','    int x, y;','    Point(int x, int y) { this.x = x; this.y = y; }'],
     placeholder:['    // TODO: 매개변수 없는 생성자에서 this(0, 0)을 호출하도록 작성'], rows:3,
     after:['}','Point p = new Point();','System.out.println(p.x + "," + p.y);'],
     expected:'0,0',
     answer:['    Point() {','        this(0, 0);','    }'], note:'',
     regex:[/Point\s*\(\s*\)\s*\{/, /this\s*\(\s*0\s*,\s*0\s*\)/]},
    {id:'CL5', level:0, title:'static 필드 — 모든 인스턴스가 공유',
     concept:'static이 붙은 필드는 인스턴스마다 따로 갖는 게 아니라, 클래스 전체에서 단 하나만 존재해서 모든 객체가 공유합니다. 객체를 만들 때마다 값을 누적하고 싶을 때 자주 씁니다.',
     before:['class Counter {','    static int count = 0;','    Counter() {'],
     placeholder:['        // TODO: 객체가 생성될 때마다 count를 1 증가'],
     after:['    }','}','new Counter(); new Counter(); new Counter();','System.out.println(Counter.count);'],
     expected:'3',
     answer:['        count++;'],
     note:'static 필드는 클래스 이름(Counter.count)으로 직접 접근할 수 있습니다.',
     regex:[/count\+\+|count\s*=\s*count\s*\+\s*1/]},
    {id:'CL6', level:0, title:'객체 배열 채우기',
     concept:'객체 타입 배열을 선언하면, 각 칸은 처음에는 객체가 아니라 null로 채워집니다. new로 배열 공간을 만든 뒤, 각 칸마다 따로 객체를 생성해서 넣어야 합니다.',
     before:['class Person {','    String name;','    Person(String name) { this.name = name; }','}','Person[] people = new Person[2];'],
     placeholder:['// TODO','// (0번 칸에 "철수", 1번 칸에 "영희" 객체를 생성해서 넣기)'], rows:3,
     after:['System.out.println(people[0].name + ", " + people[1].name);'],
     expected:'철수, 영희',
     answer:['people[0] = new Person("철수");','people[1] = new Person("영희");'], note:'',
     regex:[/people\[\s*0\s*\]\s*=\s*new\s*Person\s*\(\s*"철수"\s*\)/, /people\[\s*1\s*\]\s*=\s*new\s*Person\s*\(\s*"영희"\s*\)/]},

    /* ---------------- 2장 상속 ---------------- */,
    {id:'IH1', level:1, title:'extends로 상속',
     concept:'한 클래스가 다른 클래스의 필드와 메서드를 물려받게 하려면 extends를 씁니다. 부모(상위) 클래스의 멤버를 자식(하위) 클래스에서도 그대로 쓸 수 있습니다.',
     before:['class Animal {','    String name = "동물";','    void sound() { System.out.println("소리"); }','}'],
     placeholder:['// TODO: Animal을 상속받는 Dog 클래스 선언 (빈 클래스)'],
     after:['Dog d = new Dog();','System.out.println(d.name);','d.sound();'],
     expected:'동물, 소리',
     answer:['class Dog extends Animal {','}'], note:'',
     regex:[/class\s+Dog\s+extends\s+Animal/]},
    {id:'IH2', level:1, title:'super()로 부모 생성자 호출',
     concept:'자식 클래스의 생성자는 항상 부모 클래스의 생성자를 먼저 실행합니다. 부모 생성자에 인자를 넘기고 싶다면 super(...)를 직접 호출해야 하고, 반드시 생성자의 첫 줄이어야 합니다.',
     before:['class Animal {','    String name;','    Animal(String name) { this.name = name; }','}','class Dog extends Animal {'],
     placeholder:['    // TODO: Dog(String name) 생성자에서 super(name) 호출'], rows:3,
     after:['}','Dog d = new Dog("바둑이");','System.out.println(d.name);'],
     expected:'바둑이',
     answer:['    Dog(String name) {','        super(name);','    }'], note:'',
     regex:[/Dog\s*\(\s*String\s+name\s*\)\s*\{/, /super\s*\(\s*name\s*\)/]},
    {id:'IH3', level:1, title:'메서드 오버라이딩',
     concept:'자식 클래스에서 부모와 같은 시그니처(이름·매개변수)의 메서드를 다시 정의하면, 부모의 동작을 덮어씁니다(오버라이딩). @Override 애너테이션은 필수는 아니지만 붙이는 게 관례입니다.',
     before:['class Animal {','    void sound() { System.out.println("동물 소리"); }','}','class Cat extends Animal {'],
     placeholder:['    // TODO: sound()를 오버라이딩해서 "야옹" 출력'], rows:4,
     after:['}','Animal a = new Cat();','a.sound();'],
     expected:'야옹',
     answer:['    @Override','    void sound() {','        System.out.println("야옹");','    }'],
     note:'Animal 타입 변수에 Cat 객체를 담아도(다형성), 실제 호출되는 건 Cat의 sound()입니다 — 이를 동적 바인딩(dynamic binding)이라 합니다.',
     regex:[/void\s+sound\s*\(\s*\)\s*\{/, /야옹/]},
    {id:'IH4', level:1, title:'super.method()로 부모 메서드 호출',
     concept:'오버라이딩한 메서드 안에서도 부모의 원래 동작을 호출하고 싶을 때가 있습니다. super.메서드명()으로 부모 버전을 명시적으로 호출할 수 있습니다.',
     before:['class Animal {','    void sound() { System.out.println("동물 소리"); }','}','class Cat extends Animal {','    @Override','    void sound() {'],
     placeholder:['        // TODO: 부모의 sound()를 먼저 호출'],
     after:['        System.out.println("야옹");','    }','}','new Cat().sound();'],
     expected:'동물 소리, 야옹',
     answer:['        super.sound();'], note:'',
     regex:[/super\.sound\s*\(\s*\)/]},
    {id:'IH5', level:1, title:'instanceof로 타입 확인',
     concept:'다형적 참조 변수가 실제로 어떤 타입의 객체를 가리키고 있는지 확인하고 싶을 때 instanceof 연산자를 씁니다. 결과는 true/false입니다.',
     before:['class Animal {}','class Dog extends Animal {}','Animal a = new Dog();'],
     placeholder:['boolean isDog = /* TODO */;'],
     after:['System.out.println(isDog);'],
     expected:'true',
     answer:['boolean isDog = a instanceof Dog;'], note:'',
     regex:[/boolean\s+isDog\s*=\s*a\s+instanceof\s+Dog/]},
    {id:'IH6', level:1, title:'다형적 배열로 한 번에 처리',
     concept:'부모 타입 배열 하나에 서로 다른 자식 클래스의 객체들을 함께 담을 수 있습니다. 각 원소에서 호출하는 메서드는 실제 객체의 타입에 따라 다르게 동작합니다(다형성).',
     before:['class Animal { void sound() { System.out.println("..."); } }','class Dog extends Animal { void sound() { System.out.println("멍멍"); } }','class Cat extends Animal { void sound() { System.out.println("야옹"); } }','Animal[] animals = {new Dog(), new Cat()};'],
     placeholder:['// TODO','// (animals를 순회하며 각각 sound() 호출)'], rows:3,
     after:[],
     expected:'멍멍, 야옹',
     answer:['for (Animal a : animals) {','    a.sound();','}'], note:'',
     regex:[/for\s*\(\s*Animal\s+\w+\s*:\s*animals\s*\)/, /\.sound\s*\(\s*\)/]},
    {id:'IH7', level:1, title:'final 메서드 — 오버라이딩 금지',
     concept:'final이 붙은 메서드는 자식 클래스에서 더 이상 오버라이딩할 수 없습니다. "이 동작은 절대 바뀌면 안 된다"는 의도를 표현할 때 씁니다.',
     before:['class Animal {'],
     placeholder:['    // TODO: 절대 오버라이딩되면 안 되는 breathe() 메서드를 final로 선언하고 "숨쉬기" 출력'], rows:3,
     after:['}','new Animal().breathe();'],
     expected:'숨쉬기',
     answer:['    final void breathe() {','        System.out.println("숨쉬기");','    }'],
     note:'자식 클래스에서 같은 시그니처로 breathe()를 다시 정의하려고 하면 컴파일 에러가 납니다.',
     regex:[/final\s+void\s+breathe\s*\(\s*\)\s*\{/, /숨쉬기/]},

    /* ---------------- 3장 인터페이스 ---------------- */,
    {id:'IF1', level:2, title:'interface 정의와 구현',
     concept:'인터페이스는 메서드의 이름과 시그니처만 정의하고, 본문(구현)은 갖지 않습니다. 클래스가 implements로 인터페이스를 구현할 때는, 선언된 모든 메서드를 반드시 직접 작성해야 합니다.',
     before:['interface Flyable {','    void fly();','}','class Bird implements Flyable {'],
     placeholder:['    // TODO: fly() 구현, "날아간다" 출력'], rows:3,
     after:['}','new Bird().fly();'],
     expected:'날아간다',
     answer:['    public void fly() {','        System.out.println("날아간다");','    }'],
     note:'인터페이스의 메서드를 구현할 때는 반드시 public을 붙여야 합니다 — 인터페이스의 메서드는 기본적으로 public이기 때문에, 구현부에서 접근 제한을 더 좁힐 수 없습니다.',
     regex:[/public\s+void\s+fly\s*\(\s*\)\s*\{/, /날아간다/]},
    {id:'IF2', level:2, title:'다중 인터페이스 구현',
     concept:'클래스는 단 하나만 상속(extends)할 수 있지만, 인터페이스는 콤마로 나열해서 여러 개를 동시에 구현(implements)할 수 있습니다.',
     before:['interface Flyable { void fly(); }','interface Swimmable { void swim(); }'],
     placeholder:['// TODO: Flyable과 Swimmable을 모두 구현하는 Duck 클래스 선언','// (fly()는 "난다", swim()은 "헤엄친다" 출력)'], rows:6,
     after:['Duck d = new Duck();','d.fly();','d.swim();'],
     expected:'난다, 헤엄친다',
     answer:['class Duck implements Flyable, Swimmable {','    public void fly() { System.out.println("난다"); }','    public void swim() { System.out.println("헤엄친다"); }','}'],
     note:'extends는 하나만 가능하지만, implements는 콤마로 여러 인터페이스를 동시에 구현할 수 있습니다.',
     regex:[/class\s+Duck\s+implements\s+Flyable\s*,\s*Swimmable/, /public\s+void\s+fly\s*\(\s*\)/, /public\s+void\s+swim\s*\(\s*\)/]},
    {id:'IF3', level:2, title:'default 메서드',
     concept:'인터페이스도 default 키워드를 붙이면 본문이 있는 메서드를 가질 수 있습니다. 구현 클래스가 따로 오버라이딩하지 않으면 이 기본 동작을 그대로 물려받습니다.',
     before:['interface Greeter {'],
     placeholder:['    // TODO: 본문이 있는 default 메서드 greet()을 작성, "안녕하세요" 출력'], rows:3,
     after:['}','class Korean implements Greeter {}','new Korean().greet();'],
     expected:'안녕하세요',
     answer:['    default void greet() {','        System.out.println("안녕하세요");','    }'],
     note:'구현 클래스가 greet()을 따로 정의하지 않아도 인터페이스의 기본 동작을 그대로 사용합니다.',
     regex:[/default\s+void\s+greet\s*\(\s*\)\s*\{/, /안녕하세요/]},
    {id:'IF4', level:2, title:'인터페이스 타입으로 참조',
     concept:'인터페이스도 클래스처럼 참조 타입으로 쓸 수 있습니다. 왼쪽을 인터페이스 타입으로 선언하면, 나중에 다른 구현체로 바꿔도 나머지 코드는 그대로 둘 수 있습니다.',
     before:['interface Shape { double area(); }','class Circle implements Shape {','    double r;','    Circle(double r) { this.r = r; }','    public double area() { return Math.PI * r * r; }','}'],
     placeholder:['// TODO: Shape 타입으로 Circle(2) 객체를 가리키는 shape 변수 선언'],
     after:['System.out.println(shape.area() > 12);'],
     expected:'true',
     answer:['Shape shape = new Circle(2);'], note:'',
     regex:[/Shape\s+shape\s*=\s*new\s*Circle\s*\(\s*2\s*\)/]},
    {id:'IF5', level:2, title:'abstract class — 필드와 일반 메서드를 가질 수 있음',
     concept:'추상 클래스(abstract class)는 인터페이스와 달리 일반 필드와 생성자, 구현이 있는 일반 메서드를 가질 수 있습니다. abstract 메서드는 본문 없이 선언만 하고, 자식 클래스가 반드시 구현해야 합니다.',
     before:['abstract class Shape {','    String name;','    Shape(String name) { this.name = name; }','    abstract double area();','}','class Square extends Shape {','    double side;','    Square(double side) { super("사각형"); this.side = side; }'],
     placeholder:['    // TODO: area()를 구현 (side * side)'], rows:3,
     after:['}','Shape s = new Square(4);','System.out.println(s.name + " " + s.area());'],
     expected:'사각형 16.0',
     answer:['    double area() {','        return side * side;','    }'],
     note:'abstract class는 직접 new로 객체를 만들 수 없고, 반드시 자식 클래스를 통해서만 사용됩니다.',
     regex:[/double\s+area\s*\(\s*\)\s*\{/, /return\s+side\s*\*\s*side/]},
    {id:'IF6', level:2, title:'Comparable로 자연 순서 정의',
     concept:'Comparable<T> 인터페이스를 구현하면 객체끼리 기본적으로 어떤 순서로 비교되어야 하는지를 직접 정의할 수 있습니다. compareTo()가 음수면 자신이 앞, 양수면 상대가 앞입니다. 한 번 구현해두면 별도 비교자 없이도 정렬이 가능해집니다.',
     before:['class Person implements Comparable<Person> {','    String name; int age;','    Person(String name, int age) { this.name = name; this.age = age; }'],
     placeholder:['    // TODO: age 기준 오름차순으로 비교하는 compareTo() 구현'], rows:3,
     after:['}','List<Person> people = new ArrayList<>(Arrays.asList(new Person("A", 30), new Person("B", 20)));','Collections.sort(people);','System.out.println(people.get(0).name);'],
     expected:'B',
     answer:['    public int compareTo(Person other) {','        return this.age - other.age;','    }'], note:'',
     regex:[/public\s+int\s+compareTo\s*\(\s*Person\s+\w+\s*\)/, /this\.age\s*-\s*\w+\.age|Integer\.compare\s*\(\s*this\.age\s*,\s*\w+\.age\s*\)/]},

    /* ---------------- 4장 추상화 · 캡슐화 ---------------- */,
    {id:'AC1', level:3, title:'private 필드와 getter',
     concept:'필드를 private으로 막아두면 클래스 바깥에서 직접 접근할 수 없습니다. 대신 값을 읽을 수 있는 getter 메서드를 공개(public)로 따로 제공하는 게 캡슐화(encapsulation)의 기본 패턴입니다.',
     before:['class Account {','    private int balance = 1000;'],
     placeholder:['    // TODO: balance를 반환하는 getBalance() 작성'], rows:3,
     after:['}','Account acc = new Account();','System.out.println(acc.getBalance());'],
     expected:'1000',
     answer:['    public int getBalance() {','        return balance;','    }'], note:'',
     regex:[/public\s+int\s+getBalance\s*\(\s*\)\s*\{/, /return\s+balance/]},
    {id:'AC2', level:3, title:'setter에서 유효성 검사',
     concept:'setter 메서드 안에서 조건을 검사해 잘못된 값이 들어오는 걸 막을 수 있습니다 — 이게 필드를 public으로 그냥 열어두는 것과 캡슐화의 가장 큰 차이입니다.',
     before:['class Account {','    private int balance = 1000;','    public int getBalance() { return balance; }'],
     placeholder:['    // TODO: amount가 0 이상일 때만 balance에 더하는 deposit(int amount) 작성'], rows:5,
     after:['}','Account acc = new Account();','acc.deposit(-500);','acc.deposit(200);','System.out.println(acc.getBalance());'],
     expected:'1200',
     answer:['    public void deposit(int amount) {','        if (amount >= 0) {','            balance += amount;','        }','    }'], note:'',
     regex:[/public\s+void\s+deposit\s*\(\s*int\s+amount\s*\)\s*\{/, /if\s*\(\s*amount\s*>=\s*0\s*\)/, /balance\s*\+=\s*amount/]},
    {id:'AC3', level:3, title:'static 메서드',
     concept:'static 메서드는 객체를 만들지 않고 클래스 이름으로 바로 호출할 수 있습니다. 인스턴스 필드(객체마다 다른 값)에는 접근할 수 없고, static 필드나 매개변수로 받은 값만 다룰 수 있습니다.',
     before:['class MathUtil {'],
     placeholder:['    // TODO: 두 정수를 더해 반환하는 static 메서드 add(int a, int b) 작성'], rows:3,
     after:['}','System.out.println(MathUtil.add(3, 4));'],
     expected:'7',
     answer:['    static int add(int a, int b) {','        return a + b;','    }'], note:'',
     regex:[/static\s+int\s+add\s*\(\s*int\s+a\s*,\s*int\s+b\s*\)\s*\{/, /return\s+a\s*\+\s*b/]},
    {id:'AC4', level:3, title:'읽기 전용 필드 — getter만 제공',
     concept:'필드를 private으로 막고 getter만 제공하면, 바깥에서 값을 읽을 수는 있지만 직접 바꿀 수는 없는 읽기 전용(read-only) 속성을 만들 수 있습니다. setter를 아예 제공하지 않으면 됩니다.',
     before:['class Employee {','    private final String id;','    Employee(String id) { this.id = id; }'],
     placeholder:['    // TODO: id를 반환하는 getId() 작성 (setId는 만들지 않음)'], rows:3,
     after:['}','Employee e = new Employee("EMP01");','System.out.println(e.getId());'],
     expected:'EMP01',
     answer:['    public String getId() {','        return id;','    }'],
     note:'final이 붙은 필드는 생성자에서 딱 한 번만 값을 정할 수 있고, 이후엔 절대 바꿀 수 없습니다.',
     regex:[/public\s+String\s+getId\s*\(\s*\)\s*\{/, /return\s+id/]},
    {id:'AC5', level:3, title:'equals() 오버라이딩 — 값으로 비교',
     concept:'기본 equals()는 두 변수가 같은 객체를 가리키는지(참조 비교)만 검사합니다. 필드 값이 같으면 같은 객체로 취급하고 싶다면 equals()를 직접 오버라이딩해야 합니다.',
     before:['class Point {','    int x, y;','    Point(int x, int y) { this.x = x; this.y = y; }','    @Override'],
     placeholder:['    // TODO: x와 y가 모두 같으면 true를 반환하는 equals(Object o) 작성'], rows:5,
     after:['}','Point p1 = new Point(1, 2);','Point p2 = new Point(1, 2);','System.out.println(p1.equals(p2));'],
     expected:'true',
     answer:['    public boolean equals(Object o) {','        if (!(o instanceof Point)) return false;','        Point p = (Point) o;','        return this.x == p.x && this.y == p.y;','    }'],
     note:'equals()를 오버라이딩하면 보통 hashCode()도 함께 오버라이딩해야 HashSet/HashMap에서 일관되게 동작합니다.',
     regex:[/public\s+boolean\s+equals\s*\(\s*Object\s+\w+\s*\)\s*\{/, /instanceof\s+Point/, /this\.x\s*==\s*\w+\.x/]},
    {id:'AC6', level:3, title:'toString() 오버라이딩',
     concept:'객체를 System.out.println()으로 바로 출력하면 기본적으로 의미 없는 문자열이 나옵니다. toString()을 오버라이딩하면 원하는 형태로 직접 표현을 정의할 수 있습니다.',
     before:['class Point {','    int x, y;','    Point(int x, int y) { this.x = x; this.y = y; }'],
     placeholder:['    // TODO: "(x, y)" 형태의 문자열을 반환하는 toString() 작성'], rows:4,
     after:['}','Point p = new Point(1, 2);','System.out.println(p);'],
     expected:'(1, 2)',
     answer:['    @Override','    public String toString() {','        return "(" + x + ", " + y + ")";','    }'],
     note:'System.out.println(객체)는 내부적으로 객체의 toString()을 자동으로 호출합니다.',
     regex:[/public\s+String\s+toString\s*\(\s*\)\s*\{/, /return\s+"\("\s*\+\s*x\s*\+\s*",\s*"\s*\+\s*y\s*\+\s*"\)"/]},

    /* ---------------- 5장 람다 표현식 ---------------- */,
    {id:'V1', level:4, title:'🔁 변형: 생성자 (다른 데이터)',
     concept:'CL1과 같은 패턴입니다. 생성자에서 this로 필드를 초기화합니다.',
     before:['class Book {','    String title;','    int pages;'],
     placeholder:['    // TODO: title과 pages를 매개변수로 받아 필드를 초기화하는 생성자 작성'], rows:4,
     after:['}','Book b = new Book("자바의 정석", 700);','System.out.println(b.title + " " + b.pages);'],
     expected:'자바의 정석 700',
     answer:['    Book(String title, int pages) {','        this.title = title;','        this.pages = pages;','    }'], note:'',
     regex:[/Book\s*\(\s*String\s+title\s*,\s*int\s+pages\s*\)/, /this\.title\s*=\s*title/, /this\.pages\s*=\s*pages/]},
    {id:'V2', level:4, title:'🔁 변형: 메서드 오버라이딩 (다른 데이터)',
     concept:'IH3과 같은 메서드 오버라이딩 패턴입니다. 출력 문구만 다릅니다.',
     before:['class Animal { void sound() { System.out.println("동물 소리"); } }','class Dog extends Animal {'],
     placeholder:['    // TODO: sound()를 오버라이딩해서 "멍멍" 출력'], rows:4,
     after:['}','Animal a = new Dog();','a.sound();'],
     expected:'멍멍',
     answer:['    @Override','    void sound() {','        System.out.println("멍멍");','    }'], note:'',
     regex:[/void\s+sound\s*\(\s*\)\s*\{/, /멍멍/]},
    {id:'V3', level:4, title:'🔁 변형: 인터페이스 구현 (다른 데이터)',
     concept:'IF1과 같은 인터페이스 구현 패턴입니다.',
     before:['interface Movable {','    void move();','}','class Car implements Movable {'],
     placeholder:['    // TODO: move() 구현, "달린다" 출력'], rows:3,
     after:['}','new Car().move();'],
     expected:'달린다',
     answer:['    public void move() {','        System.out.println("달린다");','    }'], note:'',
     regex:[/public\s+void\s+move\s*\(\s*\)\s*\{/, /달린다/]},
    {id:'V4', level:4, title:'🔁 변형: setter 유효성 검사 (다른 데이터)',
     concept:'AC2와 같은 유효성 검사 setter 패턴입니다.',
     before:['class Account {','    private int balance = 0;','    public int getBalance() { return balance; }'],
     placeholder:['    // TODO: amount가 0 이상일 때만 balance에 더하는 deposit(int amount) 작성'], rows:5,
     after:['}','Account acc = new Account();','acc.deposit(1000);','acc.deposit(-300);','System.out.println(acc.getBalance());'],
     expected:'1000',
     answer:['    public void deposit(int amount) {','        if (amount >= 0) {','            balance += amount;','        }','    }'], note:'',
     regex:[/public\s+void\s+deposit\s*\(\s*int\s+amount\s*\)\s*\{/, /if\s*\(\s*amount\s*>=\s*0\s*\)/, /balance\s*\+=\s*amount/]},

  {id:'COMP1', level:5, title:'Comparator.comparingInt — 정수 기준 오름차순 정렬',
   concept:'Comparator는 정렬 기준을 외부에서 주입할 때 씁니다. comparingInt(키 추출 람다)가 가장 많이 쓰이는 패턴으로, 객체 리스트를 특정 int 속성 기준으로 정렬합니다.',
   before:['List<String> words = new ArrayList<>(Arrays.asList("banana", "kiwi", "apple", "fig"));'],
   placeholder:['// TODO: words를 문자열 길이 오름차순으로 정렬'],
   after:['System.out.println(words.get(0));'],
   expected:'fig',
   answer:['words.sort(Comparator.comparingInt(String::length));'], note:'',
   regex:[/words\.sort\s*\(/, /Comparator\.comparingInt\s*\(/]},

  {id:'COMP2', level:5, title:'Comparator — .reversed()로 내림차순',
   concept:'.reversed()를 체이닝하면 기준을 뒤집어 내림차순이 됩니다. 오름차순 Comparator를 만든 뒤 뒤집는 것이 일반적인 패턴입니다.',
   before:['List<String> words = new ArrayList<>(Arrays.asList("banana", "kiwi", "apple", "fig"));'],
   placeholder:['// TODO: words를 문자열 길이 내림차순으로 정렬'],
   after:['System.out.println(words.get(0));'],
   expected:'banana',
   answer:['words.sort(Comparator.comparingInt(String::length).reversed());'], note:'',
   regex:[/words\.sort\s*\(/, /Comparator\.comparingInt\s*\(/, /\.reversed\s*\(\s*\)/]},

  {id:'ENUM1', level:5, title:'enum — 열거형 선언과 상수 참조',
   concept:'enum은 정해진 상수 집합을 타입으로 묶을 때 씁니다. String이나 int 대신 쓰면 오타나 범위 오류를 컴파일 시점에 잡을 수 있습니다. 방향, 상태, 카테고리 표현에 자주 씁니다.',
   before:['// enum Direction { UP, DOWN, LEFT, RIGHT } 이미 선언되어 있음'],
   placeholder:['// TODO: dir을 UP으로, next를 DOWN으로 선언'],
   after:['System.out.println(dir + " " + next);'],
   expected:'UP DOWN',
   answer:['Direction dir = Direction.UP;', 'Direction next = Direction.DOWN;'], note:'',
   regex:[/Direction\s+dir\s*=\s*Direction\.UP/, /Direction\s+next\s*=\s*Direction\.DOWN/]},

  {id:'ENUM2', level:5, title:'enum — values()로 모든 상수 순회',
   concept:'enum.values()는 선언된 모든 상수를 배열로 반환합니다. for-each와 조합해 모든 상태를 처리할 때 씁니다.',
   before:['// enum Season { SPRING, SUMMER, FALL, WINTER } 이미 선언되어 있음'],
   placeholder:['// TODO: 모든 Season을 한 줄씩 출력 (values() + for-each)'],
   after:[''],
   expected:'SPRING\nSUMMER\nFALL\nWINTER',
   answer:['for (Season s : Season.values()) System.out.println(s);'], note:'',
   regex:[/Season\.values\s*\(\s*\)/, /for\s*\(\s*Season\s+\w+\s*:/]}
];
